# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mwimw1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_type_page(object):
    def setupUi(self, type_page):
        type_page.setObjectName("type_page")
        type_page.resize(800, 600)
        self.go_button = QtWidgets.QPushButton(type_page)
        self.go_button.setGeometry(QtCore.QRect(340, 400, 161, 91))
        self.go_button.setObjectName("go_button")
        self.input_box = QtWidgets.QLineEdit(type_page)
        self.input_box.setGeometry(QtCore.QRect(300, 350, 231, 21))
        self.input_box.setObjectName("input_box")
        self.type_here = QtWidgets.QLabel(type_page)
        self.type_here.setGeometry(QtCore.QRect(240, 160, 351, 141))
        self.type_here.setAlignment(QtCore.Qt.AlignCenter)
        self.type_here.setObjectName("type_here")

        self.retranslateUi(type_page)
        QtCore.QMetaObject.connectSlotsByName(type_page)

    def retranslateUi(self, type_page):
        _translate = QtCore.QCoreApplication.translate
        type_page.setWindowTitle(_translate("type_page", "Type"))
        self.go_button.setText(_translate("type_page", "Go"))
        self.type_here.setText(_translate("type_page", "TYPE HERE!!!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    type_page = QtWidgets.QWidget()
    ui = Ui_type_page()
    ui.setupUi(type_page)
    type_page.show()
    sys.exit(app.exec_())
