'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

sumOfTotal = 0
arrayOfFibNumbers = [1, 2]
sumOfAllEvens = 0

while True:
    sumOfTotal = arrayOfFibNumbers[len(arrayOfFibNumbers) - 1] + arrayOfFibNumbers[len(arrayOfFibNumbers) - 2]
    if sumOfTotal <= 4000000:
        arrayOfFibNumbers.append(sumOfTotal)
    else:
        break

for number in arrayOfFibNumbers:
    if number % 2 == 0:
        #is even
        sumOfAllEvens += number

print(sumOfAllEvens)
