# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'relayoutted.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HWTracker(object):
    def setupUi(self, HWTracker):
        HWTracker.setObjectName("HWTracker")
        HWTracker.resize(967, 724)
        HWTracker.setMinimumSize(QtCore.QSize(967, 724))
        HWTracker.setStyleSheet("QMainWindow{\n"
"    background:rgb(51, 50, 51);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(HWTracker)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.switchTab = QtWidgets.QTabWidget(self.centralwidget)
        self.switchTab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.switchTab.setObjectName("switchTab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.todoDiv = QtWidgets.QGroupBox(self.tab)
        self.todoDiv.setMaximumSize(QtCore.QSize(225, 16777215))
        self.todoDiv.setStyleSheet("QGroupBox{\n"
"    border-radius:10px;\n"
"    padding-top:10px;\n"
"    background:rgb(69, 69, 73);\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:3px;\n"
"    border: 1px solid rgb(28, 139, 255);\n"
"}\n"
"QComboBox{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox:drop-down{\n"
"    border: 0px;\n"
"    background:rgb(90, 151, 255);\n"
"}\n"
"QDateTimeEdit{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QDateTimeEdit:drop-down{\n"
"    border: 0px;\n"
"    background:rgb(90, 151, 255);\n"
"}\n"
"QSlider{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}\n"
"QDateTimeEdit:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}\n"
"QComboBox:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}\n"
"QTextEdit:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}\n"
"QSlider:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}\n"
"QRadioButton{\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius:3px;\n"
"}\n"
"QRadioButton:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}")
        self.todoDiv.setTitle("")
        self.todoDiv.setObjectName("todoDiv")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.todoDiv)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.newHomeworkGroup = QtWidgets.QGroupBox(self.todoDiv)
        self.newHomeworkGroup.setObjectName("newHomeworkGroup")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.newHomeworkGroup)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.newHWText = QtWidgets.QTextEdit(self.newHomeworkGroup)
        self.newHWText.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.newHWText.setStyleSheet("")
        self.newHWText.setObjectName("newHWText")
        self.verticalLayout_13.addWidget(self.newHWText)
        self.verticalLayout_14.addWidget(self.newHomeworkGroup)
        self.newDueGroup = QtWidgets.QGroupBox(self.todoDiv)
        self.newDueGroup.setObjectName("newDueGroup")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.newDueGroup)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.newDueTime = QtWidgets.QDateTimeEdit(self.newDueGroup)
        self.newDueTime.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.newDueTime.setObjectName("newDueTime")
        self.verticalLayout_6.addWidget(self.newDueTime)
        self.radioButton = QtWidgets.QRadioButton(self.newDueGroup)
        self.radioButton.setStyleSheet("")
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_6.addWidget(self.radioButton)
        self.verticalLayout_14.addWidget(self.newDueGroup)
        self.newDifficultyGroup = QtWidgets.QGroupBox(self.todoDiv)
        self.newDifficultyGroup.setObjectName("newDifficultyGroup")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.newDifficultyGroup)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.newDifficultySlider = QtWidgets.QSlider(self.newDifficultyGroup)
        self.newDifficultySlider.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.newDifficultySlider.setStyleSheet("")
        self.newDifficultySlider.setMaximum(10)
        self.newDifficultySlider.setOrientation(QtCore.Qt.Horizontal)
        self.newDifficultySlider.setObjectName("newDifficultySlider")
        self.verticalLayout_4.addWidget(self.newDifficultySlider)
        self.verticalLayout_14.addWidget(self.newDifficultyGroup)
        self.newClassGroup = QtWidgets.QGroupBox(self.todoDiv)
        self.newClassGroup.setObjectName("newClassGroup")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.newClassGroup)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.newClassToHW = QtWidgets.QComboBox(self.newClassGroup)
        self.newClassToHW.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.newClassToHW.setObjectName("newClassToHW")
        self.newClassToHW.addItem("")
        self.verticalLayout_12.addWidget(self.newClassToHW)
        self.verticalLayout_14.addWidget(self.newClassGroup)
        self.newAdd = QtWidgets.QPushButton(self.todoDiv)
        self.newAdd.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.newAdd.setObjectName("newAdd")
        self.verticalLayout_14.addWidget(self.newAdd)
        self.horizontalLayout_2.addWidget(self.todoDiv)
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setStyleSheet("QFrame\n"
"{\n"
"    border-radius:10px;\n"
"    padding-top:10px;\n"
"    background:rgb(69, 69, 73);\n"
"}\n"
"QGroupBox{\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    padding-top:0px;\n"
"}\n"
"QRadioButton{\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius:3px;\n"
"}\n"
"QComboBox{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox:drop-down{\n"
"    border: 0px;\n"
"    background:rgb(90, 151, 255);\n"
"}\n"
"QComboBox:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}\n"
"QRadioButton:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setStyleSheet("QGroupBox{\n"
"    border-radius:3px;\n"
"    background:rgb(77, 135, 255);\n"
"}\n"
"QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"    background:rgb(77, 135, 255);\n"
"}")
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.groupBox_21 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_21.setMaximumSize(QtCore.QSize(69, 47))
        self.groupBox_21.setTitle("")
        self.groupBox_21.setObjectName("groupBox_21")
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout(self.groupBox_21)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_16 = QtWidgets.QLabel(self.groupBox_21)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_44.addWidget(self.label_16)
        self.horizontalLayout_46.addWidget(self.groupBox_21)
        self.groupBox_20 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_20.setMaximumSize(QtCore.QSize(64, 47))
        self.groupBox_20.setTitle("")
        self.groupBox_20.setObjectName("groupBox_20")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.groupBox_20)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_15 = QtWidgets.QLabel(self.groupBox_20)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_41.addWidget(self.label_15)
        self.horizontalLayout_46.addWidget(self.groupBox_20)
        self.classinside_4 = QtWidgets.QGroupBox(self.frame_5)
        self.classinside_4.setTitle("")
        self.classinside_4.setObjectName("classinside_4")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.classinside_4)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.classname_4 = QtWidgets.QLabel(self.classinside_4)
        self.classname_4.setAlignment(QtCore.Qt.AlignCenter)
        self.classname_4.setObjectName("classname_4")
        self.horizontalLayout_40.addWidget(self.classname_4)
        self.horizontalLayout_46.addWidget(self.classinside_4)
        self.diff_4 = QtWidgets.QGroupBox(self.frame_5)
        self.diff_4.setMaximumSize(QtCore.QSize(86, 47))
        self.diff_4.setTitle("")
        self.diff_4.setObjectName("diff_4")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.diff_4)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.diffrating_4 = QtWidgets.QLabel(self.diff_4)
        self.diffrating_4.setAlignment(QtCore.Qt.AlignCenter)
        self.diffrating_4.setObjectName("diffrating_4")
        self.horizontalLayout_43.addWidget(self.diffrating_4)
        self.horizontalLayout_46.addWidget(self.diff_4)
        self.groupBox_19 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_19.setMaximumSize(QtCore.QSize(85, 47))
        self.groupBox_19.setTitle("")
        self.groupBox_19.setObjectName("groupBox_19")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_19)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.diffrating_5 = QtWidgets.QLabel(self.groupBox_19)
        self.diffrating_5.setAlignment(QtCore.Qt.AlignCenter)
        self.diffrating_5.setObjectName("diffrating_5")
        self.horizontalLayout_8.addWidget(self.diffrating_5)
        self.horizontalLayout_46.addWidget(self.groupBox_19)
        self.duein_4 = QtWidgets.QGroupBox(self.frame_5)
        self.duein_4.setMaximumSize(QtCore.QSize(55, 47))
        self.duein_4.setTitle("")
        self.duein_4.setObjectName("duein_4")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.duein_4)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.dueinName_4 = QtWidgets.QLabel(self.duein_4)
        self.dueinName_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dueinName_4.setAlignment(QtCore.Qt.AlignCenter)
        self.dueinName_4.setObjectName("dueinName_4")
        self.horizontalLayout_42.addWidget(self.dueinName_4)
        self.horizontalLayout_46.addWidget(self.duein_4)
        self.groupBox_22 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_22.setMaximumSize(QtCore.QSize(70, 71))
        self.groupBox_22.setTitle("")
        self.groupBox_22.setObjectName("groupBox_22")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout(self.groupBox_22)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_17 = QtWidgets.QLabel(self.groupBox_22)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_45.addWidget(self.label_17)
        self.horizontalLayout_46.addWidget(self.groupBox_22)
        self.verticalLayout.addWidget(self.frame_5)
        self.scrollableClassesDisplay = QtWidgets.QScrollArea(self.frame)
        self.scrollableClassesDisplay.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scrollableClassesDisplay.setStyleSheet("QGroupBox{\n"
"    border-radius:3px;\n"
"    background:rgb(77, 135, 255);\n"
"}\n"
"QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"    background:rgb(77, 135, 255);\n"
"    top-padding:0px;\n"
"}\n"
"QProgressBar{\n"
"    color:rgb(0, 255, 52);\n"
"}\n"
"QPushButton{\n"
"    border-radius:3px;\n"
"    background:rgb(77, 135, 255);\n"
"}")
        self.scrollableClassesDisplay.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollableClassesDisplay.setWidgetResizable(True)
        self.scrollableClassesDisplay.setObjectName("scrollableClassesDisplay")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 632, 405))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.classSubject = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.classSubject.setMinimumSize(QtCore.QSize(600, 72))
        self.classSubject.setMaximumSize(QtCore.QSize(16777215, 72))
        self.classSubject.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.classSubject.setFrameShadow(QtWidgets.QFrame.Raised)
        self.classSubject.setObjectName("classSubject")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.classSubject)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.ifDone = QtWidgets.QCheckBox(self.classSubject)
        self.ifDone.setMaximumSize(QtCore.QSize(20, 16777215))
        self.ifDone.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.ifDone.setText("")
        self.ifDone.setObjectName("ifDone")
        self.horizontalLayout_14.addWidget(self.ifDone)
        self.block = QtWidgets.QGroupBox(self.classSubject)
        self.block.setMaximumSize(QtCore.QSize(39, 16777215))
        self.block.setTitle("")
        self.block.setObjectName("block")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.block)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.blockName = QtWidgets.QLabel(self.block)
        self.blockName.setAlignment(QtCore.Qt.AlignCenter)
        self.blockName.setObjectName("blockName")
        self.horizontalLayout_11.addWidget(self.blockName)
        self.horizontalLayout_14.addWidget(self.block)
        self.classinside = QtWidgets.QGroupBox(self.classSubject)
        self.classinside.setTitle("")
        self.classinside.setObjectName("classinside")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.classinside)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.classname = QtWidgets.QLabel(self.classinside)
        self.classname.setAlignment(QtCore.Qt.AlignCenter)
        self.classname.setObjectName("classname")
        self.horizontalLayout_10.addWidget(self.classname)
        self.horizontalLayout_14.addWidget(self.classinside)
        self.diff = QtWidgets.QGroupBox(self.classSubject)
        self.diff.setMaximumSize(QtCore.QSize(57, 16777215))
        self.diff.setTitle("")
        self.diff.setObjectName("diff")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.diff)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.diffrating = QtWidgets.QLabel(self.diff)
        self.diffrating.setAlignment(QtCore.Qt.AlignCenter)
        self.diffrating.setObjectName("diffrating")
        self.horizontalLayout_9.addWidget(self.diffrating)
        self.horizontalLayout_14.addWidget(self.diff)
        self.groupBox_6 = QtWidgets.QGroupBox(self.classSubject)
        self.groupBox_6.setMaximumSize(QtCore.QSize(50, 71))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_6)
        self.progressBar.setMaximumSize(QtCore.QSize(95, 16777215))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background:rgb(255, 255, 255);\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_12.addWidget(self.progressBar)
        self.horizontalLayout_14.addWidget(self.groupBox_6)
        self.duein = QtWidgets.QGroupBox(self.classSubject)
        self.duein.setMaximumSize(QtCore.QSize(50, 71))
        self.duein.setTitle("")
        self.duein.setObjectName("duein")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.duein)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.dueinName = QtWidgets.QLabel(self.duein)
        self.dueinName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dueinName.setAlignment(QtCore.Qt.AlignCenter)
        self.dueinName.setObjectName("dueinName")
        self.horizontalLayout_13.addWidget(self.dueinName)
        self.horizontalLayout_14.addWidget(self.duein)
        self.frame_2 = QtWidgets.QFrame(self.classSubject)
        self.frame_2.setMaximumSize(QtCore.QSize(51, 16777215))
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 40, 38))
        self.pushButton.setMinimumSize(QtCore.QSize(40, 38))
        self.pushButton.setMaximumSize(QtCore.QSize(40, 38))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_14.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.classSubject)
        self.scrollableClassesDisplay.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollableClassesDisplay)
        self.sortBy = QtWidgets.QGroupBox(self.frame)
        self.sortBy.setObjectName("sortBy")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.sortBy)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sortDue = QtWidgets.QComboBox(self.sortBy)
        self.sortDue.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.sortDue.setObjectName("sortDue")
        self.sortDue.addItem("")
        self.sortDue.addItem("")
        self.sortDue.addItem("")
        self.horizontalLayout_3.addWidget(self.sortDue)
        self.sortAcend = QtWidgets.QComboBox(self.sortBy)
        self.sortAcend.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.sortAcend.setObjectName("sortAcend")
        self.sortAcend.addItem("")
        self.sortAcend.addItem("")
        self.horizontalLayout_3.addWidget(self.sortAcend)
        self.sortShowDone = QtWidgets.QRadioButton(self.sortBy)
        self.sortShowDone.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sortShowDone.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.sortShowDone.setObjectName("sortShowDone")
        self.horizontalLayout_3.addWidget(self.sortShowDone)
        self.verticalLayout.addWidget(self.sortBy)
        self.horizontalLayout_2.addWidget(self.frame)
        self.switchTab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.scheduleDiv = QtWidgets.QGroupBox(self.tab_2)
        self.scheduleDiv.setMaximumSize(QtCore.QSize(225, 16777215))
        self.scheduleDiv.setStyleSheet("QGroupBox{\n"
"    border-radius:10px;\n"
"    padding-top:10px;\n"
"    background:rgb(69, 69, 73);\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"QRadioButton{\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius:3px;\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:3px;\n"
"    border: 1px solid rgb(28, 139, 255);\n"
"}\n"
"QTextEdit{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QDateTimeEdit:drop-down{\n"
"    border: 0px;\n"
"    background:rgb(90, 151, 255);\n"
"}\n"
"QDateTimeEdit{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QDateTimeEdit:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}\n"
"QTextEdit:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}\n"
"QRadioButton:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}")
        self.scheduleDiv.setTitle("")
        self.scheduleDiv.setObjectName("scheduleDiv")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.scheduleDiv)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.newHomeworkGroup_2 = QtWidgets.QGroupBox(self.scheduleDiv)
        self.newHomeworkGroup_2.setObjectName("newHomeworkGroup_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.newHomeworkGroup_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.newHomeworkGroup_2)
        self.textEdit_2.setMaximumSize(QtCore.QSize(141, 30))
        self.textEdit_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_2.addWidget(self.textEdit_2, 2, 1, 1, 1)
        self.newClassName_2 = QtWidgets.QTextEdit(self.newHomeworkGroup_2)
        self.newClassName_2.setMaximumSize(QtCore.QSize(180, 60))
        self.newClassName_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.newClassName_2.setObjectName("newClassName_2")
        self.gridLayout_2.addWidget(self.newClassName_2, 0, 0, 1, 2)
        self.newHWText_2 = QtWidgets.QTextEdit(self.newHomeworkGroup_2)
        self.newHWText_2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.newHWText_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.newHWText_2.setObjectName("newHWText_2")
        self.gridLayout_2.addWidget(self.newHWText_2, 1, 0, 1, 2)
        self.textEdit_3 = QtWidgets.QTextEdit(self.newHomeworkGroup_2)
        self.textEdit_3.setMaximumSize(QtCore.QSize(50, 30))
        self.textEdit_3.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_3.setObjectName("textEdit_3")
        self.gridLayout_2.addWidget(self.textEdit_3, 2, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.newHomeworkGroup_2)
        self.newDueGroup_2 = QtWidgets.QGroupBox(self.scheduleDiv)
        self.newDueGroup_2.setObjectName("newDueGroup_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.newDueGroup_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.timeEdit_3 = QtWidgets.QTimeEdit(self.newDueGroup_2)
        self.timeEdit_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.gridLayout_3.addWidget(self.timeEdit_3, 0, 0, 1, 1)
        self.timeEdit_4 = QtWidgets.QTimeEdit(self.newDueGroup_2)
        self.timeEdit_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.gridLayout_3.addWidget(self.timeEdit_4, 0, 1, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.newDueGroup_2)
        self.radioButton_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_3.addWidget(self.radioButton_2, 1, 0, 1, 2)
        self.verticalLayout_11.addWidget(self.newDueGroup_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.scheduleDiv)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_11.addWidget(self.pushButton_5)
        self.horizontalLayout_7.addWidget(self.scheduleDiv)
        self.frame_6 = QtWidgets.QFrame(self.tab_2)
        self.frame_6.setStyleSheet("QFrame\n"
"{\n"
"    border-radius:10px;\n"
"    padding-top:10px;\n"
"    background:rgb(69, 69, 73);\n"
"}\n"
"QGroupBox{\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    padding-top:0px;\n"
"}\n"
"QComboBox:drop-down{\n"
"    border: 0px;\n"
"    background:rgb(90, 151, 255);\n"
"}\n"
"QComboBox{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_11 = QtWidgets.QFrame(self.frame_6)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 74))
        self.frame_11.setStyleSheet("QGroupBox{\n"
"    border-radius:3px;\n"
"    background:rgb(77, 135, 255);\n"
"}\n"
"QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"    background:rgb(77, 135, 255);\n"
"}")
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_17 = QtWidgets.QGroupBox(self.frame_11)
        self.groupBox_17.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox_17.setMaximumSize(QtCore.QSize(100, 16777215))
        self.groupBox_17.setTitle("")
        self.groupBox_17.setObjectName("groupBox_17")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.groupBox_17)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_13 = QtWidgets.QLabel(self.groupBox_17)
        self.label_13.setMinimumSize(QtCore.QSize(0, 20))
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_37.addWidget(self.label_13)
        self.horizontalLayout_4.addWidget(self.groupBox_17)
        self.groupBox_18 = QtWidgets.QGroupBox(self.frame_11)
        self.groupBox_18.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox_18.setMaximumSize(QtCore.QSize(100, 16777215))
        self.groupBox_18.setTitle("")
        self.groupBox_18.setObjectName("groupBox_18")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.groupBox_18)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_14 = QtWidgets.QLabel(self.groupBox_18)
        self.label_14.setMinimumSize(QtCore.QSize(0, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_38.addWidget(self.label_14)
        self.horizontalLayout_4.addWidget(self.groupBox_18)
        self.groupBox_15 = QtWidgets.QGroupBox(self.frame_11)
        self.groupBox_15.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_15.setTitle("")
        self.groupBox_15.setObjectName("groupBox_15")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_11 = QtWidgets.QLabel(self.groupBox_15)
        self.label_11.setMinimumSize(QtCore.QSize(0, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_35.addWidget(self.label_11)
        self.horizontalLayout_4.addWidget(self.groupBox_15)
        self.groupBox_11 = QtWidgets.QGroupBox(self.frame_11)
        self.groupBox_11.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_10 = QtWidgets.QLabel(self.groupBox_11)
        self.label_10.setMinimumSize(QtCore.QSize(0, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_34.addWidget(self.label_10)
        self.horizontalLayout_4.addWidget(self.groupBox_11)
        self.groupBox_16 = QtWidgets.QGroupBox(self.frame_11)
        self.groupBox_16.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox_16.setMaximumSize(QtCore.QSize(70, 16777215))
        self.groupBox_16.setTitle("")
        self.groupBox_16.setObjectName("groupBox_16")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.groupBox_16)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_12 = QtWidgets.QLabel(self.groupBox_16)
        self.label_12.setMinimumSize(QtCore.QSize(0, 20))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_36.addWidget(self.label_12)
        self.horizontalLayout_4.addWidget(self.groupBox_16)
        self.verticalLayout_5.addWidget(self.frame_11)
        self.scrollableClassesDisplay_3 = QtWidgets.QScrollArea(self.frame_6)
        self.scrollableClassesDisplay_3.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scrollableClassesDisplay_3.setStyleSheet("QGroupBox{\n"
"    border-radius:3px;\n"
"    background:rgb(77, 135, 255);\n"
"}\n"
"QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"    background:rgb(77, 135, 255);\n"
"    top-padding:0px;\n"
"}\n"
"QProgressBar{\n"
"    color:rgb(0, 255, 52);\n"
"}\n"
"QPushButton{\n"
"    border-radius:3px;\n"
"    background:rgb(77, 135, 255);\n"
"}")
        self.scrollableClassesDisplay_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollableClassesDisplay_3.setWidgetResizable(True)
        self.scrollableClassesDisplay_3.setObjectName("scrollableClassesDisplay_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 632, 405))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.classSubject_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.classSubject_2.setMinimumSize(QtCore.QSize(600, 71))
        self.classSubject_2.setMaximumSize(QtCore.QSize(16777215, 71))
        self.classSubject_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.classSubject_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.classSubject_2.setObjectName("classSubject_2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.classSubject_2)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.groupBox_9 = QtWidgets.QGroupBox(self.classSubject_2)
        self.groupBox_9.setMaximumSize(QtCore.QSize(100, 71))
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_8 = QtWidgets.QLabel(self.groupBox_9)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_33.addWidget(self.label_8)
        self.horizontalLayout_16.addWidget(self.groupBox_9)
        self.groupBox_7 = QtWidgets.QGroupBox(self.classSubject_2)
        self.groupBox_7.setMaximumSize(QtCore.QSize(50, 71))
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        self.label_6.setMinimumSize(QtCore.QSize(0, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_29.addWidget(self.label_6)
        self.horizontalLayout_16.addWidget(self.groupBox_7)
        self.groupBox_10 = QtWidgets.QGroupBox(self.classSubject_2)
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_9 = QtWidgets.QLabel(self.groupBox_10)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_30.addWidget(self.label_9)
        self.horizontalLayout_16.addWidget(self.groupBox_10)
        self.groupBox_8 = QtWidgets.QGroupBox(self.classSubject_2)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_7 = QtWidgets.QLabel(self.groupBox_8)
        self.label_7.setMinimumSize(QtCore.QSize(0, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_31.addWidget(self.label_7)
        self.horizontalLayout_16.addWidget(self.groupBox_8)
        self.pushButton_2 = QtWidgets.QPushButton(self.classSubject_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(40, 38))
        self.pushButton_2.setMaximumSize(QtCore.QSize(40, 38))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_16.addWidget(self.pushButton_2)
        self.verticalLayout_3.addWidget(self.classSubject_2)
        self.scrollableClassesDisplay_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.addWidget(self.scrollableClassesDisplay_3)
        self.sortBy_2 = QtWidgets.QGroupBox(self.frame_6)
        self.sortBy_2.setStyleSheet("")
        self.sortBy_2.setObjectName("sortBy_2")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.sortBy_2)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.sortDue_2 = QtWidgets.QComboBox(self.sortBy_2)
        self.sortDue_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.sortDue_2.setObjectName("sortDue_2")
        self.sortDue_2.addItem("")
        self.sortDue_2.addItem("")
        self.sortDue_2.addItem("")
        self.horizontalLayout_27.addWidget(self.sortDue_2)
        self.sortAcend_2 = QtWidgets.QComboBox(self.sortBy_2)
        self.sortAcend_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.sortAcend_2.setObjectName("sortAcend_2")
        self.sortAcend_2.addItem("")
        self.sortAcend_2.addItem("")
        self.horizontalLayout_27.addWidget(self.sortAcend_2)
        self.verticalLayout_5.addWidget(self.sortBy_2)
        self.horizontalLayout_7.addWidget(self.frame_6)
        self.switchTab.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.switchTab)
        HWTracker.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HWTracker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 967, 22))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuImport_Calendar = QtWidgets.QMenu(self.menuFile)
        self.menuImport_Calendar.setObjectName("menuImport_Calendar")
        self.menuHow_to_use = QtWidgets.QMenu(self.menubar)
        self.menuHow_to_use.setObjectName("menuHow_to_use")
        self.menuAppearence = QtWidgets.QMenu(self.menubar)
        self.menuAppearence.setObjectName("menuAppearence")
        self.menuEnter_Fullscreen = QtWidgets.QMenu(self.menuAppearence)
        self.menuEnter_Fullscreen.setObjectName("menuEnter_Fullscreen")
        self.menuThemes = QtWidgets.QMenu(self.menuAppearence)
        self.menuThemes.setObjectName("menuThemes")
        self.menuDark_Mode_yesss = QtWidgets.QMenu(self.menuThemes)
        self.menuDark_Mode_yesss.setObjectName("menuDark_Mode_yesss")
        self.menuLight_Mode_meh = QtWidgets.QMenu(self.menuThemes)
        self.menuLight_Mode_meh.setObjectName("menuLight_Mode_meh")
        self.menuCustom_2 = QtWidgets.QMenu(self.menuThemes)
        self.menuCustom_2.setObjectName("menuCustom_2")
        self.menuNew = QtWidgets.QMenu(self.menubar)
        self.menuNew.setObjectName("menuNew")
        HWTracker.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HWTracker)
        self.statusbar.setObjectName("statusbar")
        HWTracker.setStatusBar(self.statusbar)
        self.actionAdd_class = QtWidgets.QAction(HWTracker)
        self.actionAdd_class.setObjectName("actionAdd_class")
        self.actionAdd_work = QtWidgets.QAction(HWTracker)
        self.actionAdd_work.setObjectName("actionAdd_work")
        self.actionMake_New = QtWidgets.QAction(HWTracker)
        self.actionMake_New.setObjectName("actionMake_New")
        self.actionExample = QtWidgets.QAction(HWTracker)
        self.actionExample.setObjectName("actionExample")
        self.actionDark_Chocolate = QtWidgets.QAction(HWTracker)
        self.actionDark_Chocolate.setObjectName("actionDark_Chocolate")
        self.actionNight_Sky = QtWidgets.QAction(HWTracker)
        self.actionNight_Sky.setObjectName("actionNight_Sky")
        self.actionChocolate = QtWidgets.QAction(HWTracker)
        self.actionChocolate.setObjectName("actionChocolate")
        self.action500_Shades_Of_Grey = QtWidgets.QAction(HWTracker)
        self.action500_Shades_Of_Grey.setObjectName("action500_Shades_Of_Grey")
        self.actionContrast = QtWidgets.QAction(HWTracker)
        self.actionContrast.setObjectName("actionContrast")
        self.actionNuclear_Explosion = QtWidgets.QAction(HWTracker)
        self.actionNuclear_Explosion.setObjectName("actionNuclear_Explosion")
        self.actionSilk = QtWidgets.QAction(HWTracker)
        self.actionSilk.setObjectName("actionSilk")
        self.actionPaper = QtWidgets.QAction(HWTracker)
        self.actionPaper.setObjectName("actionPaper")
        self.actionMilk = QtWidgets.QAction(HWTracker)
        self.actionMilk.setObjectName("actionMilk")
        self.actionInverse_Contrast = QtWidgets.QAction(HWTracker)
        self.actionInverse_Contrast.setObjectName("actionInverse_Contrast")
        self.actionHow_to_use = QtWidgets.QAction(HWTracker)
        self.actionHow_to_use.setObjectName("actionHow_to_use")
        self.actionSave = QtWidgets.QAction(HWTracker)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_Calendar_As = QtWidgets.QAction(HWTracker)
        self.actionSave_Calendar_As.setObjectName("actionSave_Calendar_As")
        self.actionTodo = QtWidgets.QAction(HWTracker)
        self.actionTodo.setObjectName("actionTodo")
        self.actionClasses = QtWidgets.QAction(HWTracker)
        self.actionClasses.setObjectName("actionClasses")
        self.actiongoogle = QtWidgets.QAction(HWTracker)
        self.actiongoogle.setObjectName("actiongoogle")
        self.actionfile = QtWidgets.QAction(HWTracker)
        self.actionfile.setObjectName("actionfile")
        self.actionAbout = QtWidgets.QAction(HWTracker)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_2 = QtWidgets.QAction(HWTracker)
        self.actionAbout_2.setObjectName("actionAbout_2")
        self.actionType_Here = QtWidgets.QAction(HWTracker)
        self.actionType_Here.setObjectName("actionType_Here")
        self.actionCave = QtWidgets.QAction(HWTracker)
        self.actionCave.setObjectName("actionCave")
        self.actionDark_Chocolate_2 = QtWidgets.QAction(HWTracker)
        self.actionDark_Chocolate_2.setObjectName("actionDark_Chocolate_2")
        self.action51_Shades_Of_Light_Black = QtWidgets.QAction(HWTracker)
        self.action51_Shades_Of_Light_Black.setObjectName("action51_Shades_Of_Light_Black")
        self.actionMooclear_Explosion = QtWidgets.QAction(HWTracker)
        self.actionMooclear_Explosion.setObjectName("actionMooclear_Explosion")
        self.actionMilky = QtWidgets.QAction(HWTracker)
        self.actionMilky.setObjectName("actionMilky")
        self.actionDefault = QtWidgets.QAction(HWTracker)
        self.actionDefault.setObjectName("actionDefault")
        self.actionCreate_Your_Own = QtWidgets.QAction(HWTracker)
        self.actionCreate_Your_Own.setObjectName("actionCreate_Your_Own")
        self.actionExample_2 = QtWidgets.QAction(HWTracker)
        self.actionExample_2.setObjectName("actionExample_2")
        self.actionExit = QtWidgets.QAction(HWTracker)
        self.actionExit.setObjectName("actionExit")
        self.actionEnter_Fullscreen = QtWidgets.QAction(HWTracker)
        self.actionEnter_Fullscreen.setObjectName("actionEnter_Fullscreen")
        self.actionSettings = QtWidgets.QAction(HWTracker)
        self.actionSettings.setObjectName("actionSettings")
        self.actionhomework = QtWidgets.QAction(HWTracker)
        self.actionhomework.setCheckable(True)
        self.actionhomework.setChecked(True)
        self.actionhomework.setObjectName("actionhomework")
        self.actionclass = QtWidgets.QAction(HWTracker)
        self.actionclass.setCheckable(True)
        self.actionclass.setChecked(True)
        self.actionclass.setObjectName("actionclass")
        self.menuSettings.addAction(self.actionAbout_2)
        self.menuSettings.addAction(self.actionSettings)
        self.menuImport_Calendar.addAction(self.actionfile)
        self.menuImport_Calendar.addAction(self.actiongoogle)
        self.menuFile.addAction(self.menuImport_Calendar.menuAction())
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_Calendar_As)
        self.menuEnter_Fullscreen.addAction(self.actionEnter_Fullscreen)
        self.menuEnter_Fullscreen.addAction(self.actionExit)
        self.menuDark_Mode_yesss.addAction(self.actionCave)
        self.menuDark_Mode_yesss.addAction(self.actionDark_Chocolate_2)
        self.menuDark_Mode_yesss.addAction(self.action51_Shades_Of_Light_Black)
        self.menuLight_Mode_meh.addAction(self.actionMooclear_Explosion)
        self.menuLight_Mode_meh.addAction(self.actionMilky)
        self.menuLight_Mode_meh.addAction(self.actionDefault)
        self.menuCustom_2.addAction(self.actionCreate_Your_Own)
        self.menuCustom_2.addAction(self.actionExample_2)
        self.menuThemes.addAction(self.menuDark_Mode_yesss.menuAction())
        self.menuThemes.addAction(self.menuLight_Mode_meh.menuAction())
        self.menuThemes.addSeparator()
        self.menuThemes.addAction(self.menuCustom_2.menuAction())
        self.menuAppearence.addAction(self.menuEnter_Fullscreen.menuAction())
        self.menuAppearence.addAction(self.menuThemes.menuAction())
        self.menuAppearence.addAction(self.actionAbout)
        self.menuNew.addAction(self.actionhomework)
        self.menuNew.addAction(self.actionclass)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuNew.menuAction())
        self.menubar.addAction(self.menuAppearence.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHow_to_use.menuAction())

        self.retranslateUi(HWTracker)
        self.switchTab.setCurrentIndex(0)
        self.actionEnter_Fullscreen.triggered.connect(HWTracker.showFullScreen)
        self.actionExit.triggered.connect(HWTracker.showNormal)
        self.actionclass.triggered['bool'].connect(self.todoDiv.setVisible)
        self.actionhomework.triggered['bool'].connect(self.scheduleDiv.setVisible)
        QtCore.QMetaObject.connectSlotsByName(HWTracker)

    def retranslateUi(self, HWTracker):
        _translate = QtCore.QCoreApplication.translate
        HWTracker.setWindowTitle(_translate("HWTracker", "HWTracker V1.0"))
        self.newHomeworkGroup.setTitle(_translate("HWTracker", "Homework"))
        self.newHWText.setHtml(_translate("HWTracker", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.newHWText.setPlaceholderText(_translate("HWTracker", "Describe your homework... Does it fly? Is it blue? etc "))
        self.newDueGroup.setTitle(_translate("HWTracker", "Due Date"))
        self.radioButton.setText(_translate("HWTracker", "Assignment Repeats?"))
        self.newDifficultyGroup.setTitle(_translate("HWTracker", "Difficulty"))
        self.newClassGroup.setTitle(_translate("HWTracker", "Class"))
        self.newClassToHW.setItemText(0, _translate("HWTracker", "Comp Sci "))
        self.newAdd.setText(_translate("HWTracker", "Add"))
        self.label_16.setText(_translate("HWTracker", "Done?"))
        self.label_15.setText(_translate("HWTracker", "Block"))
        self.classname_4.setText(_translate("HWTracker", "Class"))
        self.diffrating_4.setText(_translate("HWTracker", "Difficulty"))
        self.diffrating_5.setText(_translate("HWTracker", "Progress"))
        self.dueinName_4.setText(_translate("HWTracker", "Due"))
        self.label_17.setText(_translate("HWTracker", "Info"))
        self.blockName.setText(_translate("HWTracker", "A"))
        self.classname.setText(_translate("HWTracker", "AP Computer Science"))
        self.diffrating.setText(_translate("HWTracker", "6/10"))
        self.dueinName.setText(_translate("HWTracker", "1d"))
        self.pushButton.setText(_translate("HWTracker", "..."))
        self.sortBy.setTitle(_translate("HWTracker", "Sort By:"))
        self.sortDue.setItemText(0, _translate("HWTracker", "Due Date"))
        self.sortDue.setItemText(1, _translate("HWTracker", "Class"))
        self.sortDue.setItemText(2, _translate("HWTracker", "Difficulty"))
        self.sortAcend.setItemText(0, _translate("HWTracker", "Ascending (A-Z, 1-10)"))
        self.sortAcend.setItemText(1, _translate("HWTracker", "Decending (Z-A, 10-1)"))
        self.sortShowDone.setText(_translate("HWTracker", "Show done"))
        self.switchTab.setTabText(self.switchTab.indexOf(self.tab), _translate("HWTracker", "Todo List"))
        self.newHomeworkGroup_2.setTitle(_translate("HWTracker", "Description"))
        self.textEdit_2.setPlaceholderText(_translate("HWTracker", "Classroom number"))
        self.newClassName_2.setHtml(_translate("HWTracker", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.newClassName_2.setPlaceholderText(_translate("HWTracker", "Class Name"))
        self.newHWText_2.setHtml(_translate("HWTracker", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.newHWText_2.setPlaceholderText(_translate("HWTracker", "Describe your class... Does it eat? Is it pink? etc "))
        self.textEdit_3.setPlaceholderText(_translate("HWTracker", "Block"))
        self.newDueGroup_2.setTitle(_translate("HWTracker", "Time Starts        Time Ends"))
        self.radioButton_2.setText(_translate("HWTracker", "Custom (swap schedule)"))
        self.pushButton_5.setText(_translate("HWTracker", "Add"))
        self.label_13.setText(_translate("HWTracker", "Time"))
        self.label_14.setText(_translate("HWTracker", "Block"))
        self.label_11.setText(_translate("HWTracker", "Classroom #"))
        self.label_10.setText(_translate("HWTracker", "Class"))
        self.label_12.setText(_translate("HWTracker", "Info"))
        self.label_8.setText(_translate("HWTracker", "11:45-12:01"))
        self.label_6.setText(_translate("HWTracker", "A"))
        self.label_9.setText(_translate("HWTracker", "LC 7"))
        self.label_7.setText(_translate("HWTracker", "AP Computer Science"))
        self.pushButton_2.setText(_translate("HWTracker", "..."))
        self.sortBy_2.setTitle(_translate("HWTracker", "Sort By:"))
        self.sortDue_2.setItemText(0, _translate("HWTracker", "Time"))
        self.sortDue_2.setItemText(1, _translate("HWTracker", "Class"))
        self.sortDue_2.setItemText(2, _translate("HWTracker", "Block"))
        self.sortAcend_2.setItemText(0, _translate("HWTracker", "Ascending (A-Z, 1-10)"))
        self.sortAcend_2.setItemText(1, _translate("HWTracker", "Decending (Z-A, 10-1)"))
        self.switchTab.setTabText(self.switchTab.indexOf(self.tab_2), _translate("HWTracker", "Schedule"))
        self.menuSettings.setTitle(_translate("HWTracker", "Options"))
        self.menuFile.setTitle(_translate("HWTracker", "File"))
        self.menuImport_Calendar.setTitle(_translate("HWTracker", "Import Calendar"))
        self.menuHow_to_use.setTitle(_translate("HWTracker", "How to use"))
        self.menuAppearence.setTitle(_translate("HWTracker", "Appearance"))
        self.menuEnter_Fullscreen.setTitle(_translate("HWTracker", "Fullscreen"))
        self.menuThemes.setTitle(_translate("HWTracker", "Themes"))
        self.menuDark_Mode_yesss.setTitle(_translate("HWTracker", "Dark Mode (yesss)"))
        self.menuLight_Mode_meh.setTitle(_translate("HWTracker", "Light Mode (meh)"))
        self.menuCustom_2.setTitle(_translate("HWTracker", "Custom"))
        self.menuNew.setTitle(_translate("HWTracker", "Sidebars"))
        self.actionAdd_class.setText(_translate("HWTracker", "Add class"))
        self.actionAdd_work.setText(_translate("HWTracker", "Add work"))
        self.actionMake_New.setText(_translate("HWTracker", "Make New"))
        self.actionExample.setText(_translate("HWTracker", "Example"))
        self.actionDark_Chocolate.setText(_translate("HWTracker", "Cave"))
        self.actionNight_Sky.setText(_translate("HWTracker", "Night Sky"))
        self.actionChocolate.setText(_translate("HWTracker", "Dark Chocolate"))
        self.action500_Shades_Of_Grey.setText(_translate("HWTracker", "51 Shades Of Grey"))
        self.actionContrast.setText(_translate("HWTracker", "Contrast"))
        self.actionNuclear_Explosion.setText(_translate("HWTracker", "Nuclear Explosion"))
        self.actionSilk.setText(_translate("HWTracker", "Cloud"))
        self.actionPaper.setText(_translate("HWTracker", "Paper"))
        self.actionMilk.setText(_translate("HWTracker", "Milk (Default)"))
        self.actionInverse_Contrast.setText(_translate("HWTracker", "Inverse Contrast"))
        self.actionHow_to_use.setText(_translate("HWTracker", "How to use"))
        self.actionSave.setText(_translate("HWTracker", "Save Calendar"))
        self.actionSave_Calendar_As.setText(_translate("HWTracker", "Save Calendar As"))
        self.actionTodo.setText(_translate("HWTracker", "Todo"))
        self.actionClasses.setText(_translate("HWTracker", "Classes"))
        self.actiongoogle.setText(_translate("HWTracker", "google"))
        self.actionfile.setText(_translate("HWTracker", "file"))
        self.actionAbout.setText(_translate("HWTracker", "Help"))
        self.actionAbout_2.setText(_translate("HWTracker", "About"))
        self.actionType_Here.setText(_translate("HWTracker", "Type Here"))
        self.actionCave.setText(_translate("HWTracker", "Blue Cave (default)"))
        self.actionDark_Chocolate_2.setText(_translate("HWTracker", "Dark Chocolate"))
        self.action51_Shades_Of_Light_Black.setText(_translate("HWTracker", "51 Shades Of Light Black"))
        self.actionMooclear_Explosion.setText(_translate("HWTracker", "Mooclear Explosion"))
        self.actionMilky.setText(_translate("HWTracker", "Cloud"))
        self.actionDefault.setText(_translate("HWTracker", "Milky"))
        self.actionCreate_Your_Own.setText(_translate("HWTracker", "Create Your Own"))
        self.actionExample_2.setText(_translate("HWTracker", "Example"))
        self.actionExit.setText(_translate("HWTracker", "Exit Fullscreen"))
        self.actionExit.setShortcut(_translate("HWTracker", "Ctrl+F12"))
        self.actionEnter_Fullscreen.setText(_translate("HWTracker", "Enter Fullscreen"))
        self.actionEnter_Fullscreen.setShortcut(_translate("HWTracker", "Ctrl+F11"))
        self.actionSettings.setText(_translate("HWTracker", "Settings"))
        self.actionhomework.setText(_translate("HWTracker", "homework"))
        self.actionclass.setText(_translate("HWTracker", "class"))


def Open(isOnline):
        #isonline you dont need to worry about, if it is online then we will access the database
        import sys
        app = QtWidgets.QApplication(sys.argv)
        HWTracker = QtWidgets.QMainWindow()
        ui = Ui_HWTracker()
        ui.setupUi(HWTracker)
        HWTracker.show()
        sys.exit(app.exec_())

        if not isOnline:
                import filehandler
                todos = filehandler.File.getFileContents("todos.json")
                schedule = filehandler.File.getFileContents("classes.json")
        else:
                pass #access database here
