# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'relayoutted.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HWTracker(object):
    def setupUi(self, HWTracker):
        HWTracker.setObjectName("HWTracker")
        HWTracker.resize(967, 724)
        HWTracker.setMinimumSize(QtCore.QSize(967, 724))
        HWTracker.setStyleSheet("QMainWindow{\n"
"    background:rgb(51, 50, 51);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(HWTracker)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.switchTab = QtWidgets.QTabWidget(self.centralwidget)
        self.switchTab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.switchTab.setObjectName("switchTab")
        self.todotab = QtWidgets.QWidget()
        self.todotab.setObjectName("todotab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.todotab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.todoDiv = QtWidgets.QGroupBox(self.todotab)
        self.todoDiv.setMaximumSize(QtCore.QSize(225, 16777215))
        self.todoDiv.setStyleSheet("QGroupBox{\n"
"    border-radius:10px;\n"
"    padding-top:10px;\n"
"    background:rgb(69, 69, 73);\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:3px;\n"
"    border: 1px solid rgb(28, 139, 255);\n"
"}\n"
"QComboBox{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox:drop-down{\n"
"    border: 0px;\n"
"    background:rgb(90, 151, 255);\n"
"}\n"
"QDateTimeEdit{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QDateTimeEdit:drop-down{\n"
"    border: 0px;\n"
"    background:rgb(90, 151, 255);\n"
"}\n"
"QSlider{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}\n"
"QDateTimeEdit:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}\n"
"QComboBox:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}\n"
"QTextEdit:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}\n"
"QSlider:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}\n"
"QRadioButton{\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius:3px;\n"
"}\n"
"QRadioButton:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}")
        self.todoDiv.setTitle("")
        self.todoDiv.setObjectName("todoDiv")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.todoDiv)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.newHomeworkGroup = QtWidgets.QGroupBox(self.todoDiv)
        self.newHomeworkGroup.setObjectName("newHomeworkGroup")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.newHomeworkGroup)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.newHWText = QtWidgets.QTextEdit(self.newHomeworkGroup)
        self.newHWText.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.newHWText.setStyleSheet("")
        self.newHWText.setObjectName("newHWText")
        self.verticalLayout_13.addWidget(self.newHWText)
        self.verticalLayout_14.addWidget(self.newHomeworkGroup)
        self.newDueGroup = QtWidgets.QGroupBox(self.todoDiv)
        self.newDueGroup.setObjectName("newDueGroup")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.newDueGroup)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.newDueTime = QtWidgets.QDateTimeEdit(self.newDueGroup)
        self.newDueTime.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.newDueTime.setObjectName("newDueTime")
        self.verticalLayout_6.addWidget(self.newDueTime)
        self.radioButton = QtWidgets.QRadioButton(self.newDueGroup)
        self.radioButton.setStyleSheet("")
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_6.addWidget(self.radioButton)
        self.verticalLayout_14.addWidget(self.newDueGroup)
        self.newDifficultyGroup = QtWidgets.QGroupBox(self.todoDiv)
        self.newDifficultyGroup.setObjectName("newDifficultyGroup")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.newDifficultyGroup)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.newDifficultySlider = QtWidgets.QSlider(self.newDifficultyGroup)
        self.newDifficultySlider.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.newDifficultySlider.setStyleSheet("")
        self.newDifficultySlider.setMaximum(10)
        self.newDifficultySlider.setOrientation(QtCore.Qt.Horizontal)
        self.newDifficultySlider.setObjectName("newDifficultySlider")
        self.verticalLayout_4.addWidget(self.newDifficultySlider)
        self.verticalLayout_14.addWidget(self.newDifficultyGroup)
        self.newClassGroup = QtWidgets.QGroupBox(self.todoDiv)
        self.newClassGroup.setObjectName("newClassGroup")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.newClassGroup)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.newClassToHW = QtWidgets.QComboBox(self.newClassGroup)
        self.newClassToHW.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.newClassToHW.setObjectName("newClassToHW")
        self.newClassToHW.addItem("")
        self.verticalLayout_12.addWidget(self.newClassToHW)
        self.verticalLayout_14.addWidget(self.newClassGroup)
        self.newAdd = QtWidgets.QPushButton(self.todoDiv)
        self.newAdd.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.newAdd.setObjectName("newAdd")
        self.verticalLayout_14.addWidget(self.newAdd)
        self.horizontalLayout_2.addWidget(self.todoDiv)
        self.RightSideTodo = QtWidgets.QFrame(self.todotab)
        self.RightSideTodo.setStyleSheet("QFrame\n"
"{\n"
"    border-radius:10px;\n"
"    padding-top:10px;\n"
"    background:rgb(69, 69, 73);\n"
"}\n"
"QGroupBox{\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    padding-top:0px;\n"
"}\n"
"QRadioButton{\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius:3px;\n"
"}\n"
"QComboBox{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox:drop-down{\n"
"    border: 0px;\n"
"    background:rgb(90, 151, 255);\n"
"}\n"
"QComboBox:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}\n"
"QRadioButton:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}")
        self.RightSideTodo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RightSideTodo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RightSideTodo.setObjectName("RightSideTodo")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.RightSideTodo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topbar = QtWidgets.QFrame(self.RightSideTodo)
        self.topbar.setStyleSheet("QGroupBox{\n"
"    border-radius:3px;\n"
"    background:rgb(77, 135, 255);\n"
"}\n"
"QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"    background:rgb(77, 135, 255);\n"
"}")
        self.topbar.setObjectName("topbar")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout(self.topbar)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.donetodo = QtWidgets.QGroupBox(self.topbar)
        self.donetodo.setMaximumSize(QtCore.QSize(69, 47))
        self.donetodo.setTitle("")
        self.donetodo.setObjectName("donetodo")
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout(self.donetodo)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.donenametodo = QtWidgets.QLabel(self.donetodo)
        self.donenametodo.setAlignment(QtCore.Qt.AlignCenter)
        self.donenametodo.setObjectName("donenametodo")
        self.horizontalLayout_44.addWidget(self.donenametodo)
        self.horizontalLayout_46.addWidget(self.donetodo)
        self.blocktodo = QtWidgets.QGroupBox(self.topbar)
        self.blocktodo.setMaximumSize(QtCore.QSize(64, 47))
        self.blocktodo.setTitle("")
        self.blocktodo.setObjectName("blocktodo")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.blocktodo)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.blocknametodo = QtWidgets.QLabel(self.blocktodo)
        self.blocknametodo.setAlignment(QtCore.Qt.AlignCenter)
        self.blocknametodo.setObjectName("blocknametodo")
        self.horizontalLayout_41.addWidget(self.blocknametodo)
        self.horizontalLayout_46.addWidget(self.blocktodo)
        self.classinsidetodo = QtWidgets.QGroupBox(self.topbar)
        self.classinsidetodo.setTitle("")
        self.classinsidetodo.setObjectName("classinsidetodo")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.classinsidetodo)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.classnametodo = QtWidgets.QLabel(self.classinsidetodo)
        self.classnametodo.setAlignment(QtCore.Qt.AlignCenter)
        self.classnametodo.setObjectName("classnametodo")
        self.horizontalLayout_40.addWidget(self.classnametodo)
        self.horizontalLayout_46.addWidget(self.classinsidetodo)
        self.difftodo = QtWidgets.QGroupBox(self.topbar)
        self.difftodo.setMaximumSize(QtCore.QSize(86, 47))
        self.difftodo.setTitle("")
        self.difftodo.setObjectName("difftodo")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.difftodo)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.diffratingtodo = QtWidgets.QLabel(self.difftodo)
        self.diffratingtodo.setAlignment(QtCore.Qt.AlignCenter)
        self.diffratingtodo.setObjectName("diffratingtodo")
        self.horizontalLayout_43.addWidget(self.diffratingtodo)
        self.horizontalLayout_46.addWidget(self.difftodo)
        self.progresstodo = QtWidgets.QGroupBox(self.topbar)
        self.progresstodo.setMaximumSize(QtCore.QSize(85, 47))
        self.progresstodo.setTitle("")
        self.progresstodo.setObjectName("progresstodo")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.progresstodo)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.progressbartodo = QtWidgets.QLabel(self.progresstodo)
        self.progressbartodo.setAlignment(QtCore.Qt.AlignCenter)
        self.progressbartodo.setObjectName("progressbartodo")
        self.horizontalLayout_8.addWidget(self.progressbartodo)
        self.horizontalLayout_46.addWidget(self.progresstodo)
        self.dueintodo = QtWidgets.QGroupBox(self.topbar)
        self.dueintodo.setMaximumSize(QtCore.QSize(55, 47))
        self.dueintodo.setTitle("")
        self.dueintodo.setObjectName("dueintodo")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.dueintodo)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.dueinnametodo = QtWidgets.QLabel(self.dueintodo)
        self.dueinnametodo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dueinnametodo.setAlignment(QtCore.Qt.AlignCenter)
        self.dueinnametodo.setObjectName("dueinnametodo")
        self.horizontalLayout_42.addWidget(self.dueinnametodo)
        self.horizontalLayout_46.addWidget(self.dueintodo)
        self.infotodo = QtWidgets.QGroupBox(self.topbar)
        self.infotodo.setMaximumSize(QtCore.QSize(70, 71))
        self.infotodo.setTitle("")
        self.infotodo.setObjectName("infotodo")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout(self.infotodo)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.infonametodo = QtWidgets.QLabel(self.infotodo)
        self.infonametodo.setAlignment(QtCore.Qt.AlignCenter)
        self.infonametodo.setObjectName("infonametodo")
        self.horizontalLayout_45.addWidget(self.infonametodo)
        self.horizontalLayout_46.addWidget(self.infotodo)
        self.verticalLayout.addWidget(self.topbar)
        self.scrollableHomeworkDisplay = QtWidgets.QScrollArea(self.RightSideTodo)
        self.scrollableHomeworkDisplay.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scrollableHomeworkDisplay.setStyleSheet("QGroupBox{\n"
"    border-radius:3px;\n"
"    background:rgb(77, 135, 255);\n"
"}\n"
"QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"    background:rgb(77, 135, 255);\n"
"}\n"
"QProgressBar{\n"
"    color:rgb(0, 255, 52);\n"
"}\n"
"QPushButton{\n"
"    border-radius:3px;\n"
"    background:rgb(77, 135, 255);\n"
"}")
        self.scrollableHomeworkDisplay.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollableHomeworkDisplay.setWidgetResizable(True)
        self.scrollableHomeworkDisplay.setObjectName("scrollableHomeworkDisplay")
        self.sortBy = QtWidgets.QGroupBox(self.RightSideTodo)
        self.sortBy.setObjectName("sortBy")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.sortBy)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sortDue = QtWidgets.QComboBox(self.sortBy)
        self.sortDue.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.sortDue.setObjectName("sortDue")
        self.sortDue.addItem("")
        self.sortDue.addItem("")
        self.sortDue.addItem("")
        self.horizontalLayout_3.addWidget(self.sortDue)
        self.sortAcend = QtWidgets.QComboBox(self.sortBy)
        self.sortAcend.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.sortAcend.setObjectName("sortAcend")
        self.sortAcend.addItem("")
        self.sortAcend.addItem("")
        self.horizontalLayout_3.addWidget(self.sortAcend)
        self.sortShowDone = QtWidgets.QRadioButton(self.sortBy)
        self.sortShowDone.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sortShowDone.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.sortShowDone.setObjectName("sortShowDone")
        self.horizontalLayout_3.addWidget(self.sortShowDone)
        self.verticalLayout.addWidget(self.sortBy)
        self.horizontalLayout_2.addWidget(self.RightSideTodo)
        self.switchTab.addTab(self.todotab, "")
        self.scheduletab = QtWidgets.QWidget()
        self.scheduletab.setObjectName("scheduletab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.scheduletab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.scheduleDiv = QtWidgets.QGroupBox(self.scheduletab)
        self.scheduleDiv.setMaximumSize(QtCore.QSize(225, 16777215))
        self.scheduleDiv.setStyleSheet("QGroupBox{\n"
"    border-radius:10px;\n"
"    padding-top:10px;\n"
"    background:rgb(69, 69, 73);\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"QRadioButton{\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius:3px;\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:3px;\n"
"    border: 1px solid rgb(28, 139, 255);\n"
"}\n"
"QTextEdit{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QDateTimeEdit:drop-down{\n"
"    border: 0px;\n"
"    background:rgb(90, 151, 255);\n"
"}\n"
"QDateTimeEdit{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QDateTimeEdit:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}\n"
"QTextEdit:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}\n"
"QRadioButton:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}")
        self.scheduleDiv.setTitle("")
        self.scheduleDiv.setObjectName("scheduleDiv")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.scheduleDiv)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.NewClassGroup = QtWidgets.QGroupBox(self.scheduleDiv)
        self.NewClassGroup.setObjectName("NewClassGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.NewClassGroup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.newClassroomNum = QtWidgets.QTextEdit(self.NewClassGroup)
        self.newClassroomNum.setMaximumSize(QtCore.QSize(141, 30))
        self.newClassroomNum.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.newClassroomNum.setObjectName("newClassroomNum")
        self.gridLayout_2.addWidget(self.newClassroomNum, 2, 1, 1, 1)
        self.newClassName_2 = QtWidgets.QTextEdit(self.NewClassGroup)
        self.newClassName_2.setMaximumSize(QtCore.QSize(180, 60))
        self.newClassName_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.newClassName_2.setObjectName("newClassName_2")
        self.gridLayout_2.addWidget(self.newClassName_2, 0, 0, 1, 2)
        self.newClassDesc = QtWidgets.QTextEdit(self.NewClassGroup)
        self.newClassDesc.setMaximumSize(QtCore.QSize(180, 16777215))
        self.newClassDesc.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.newClassDesc.setObjectName("newClassDesc")
        self.gridLayout_2.addWidget(self.newClassDesc, 1, 0, 1, 2)
        self.newBlock = QtWidgets.QTextEdit(self.NewClassGroup)
        self.newBlock.setMaximumSize(QtCore.QSize(50, 30))
        self.newBlock.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.newBlock.setObjectName("newBlock")
        self.gridLayout_2.addWidget(self.newBlock, 2, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.NewClassGroup)
        self.classstartdonetime = QtWidgets.QGroupBox(self.scheduleDiv)
        self.classstartdonetime.setObjectName("classstartdonetime")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.classstartdonetime)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.starts = QtWidgets.QTimeEdit(self.classstartdonetime)
        self.starts.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.starts.setObjectName("starts")
        self.gridLayout_3.addWidget(self.starts, 0, 0, 1, 1)
        self.done = QtWidgets.QTimeEdit(self.classstartdonetime)
        self.done.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.done.setObjectName("done")
        self.gridLayout_3.addWidget(self.done, 0, 1, 1, 1)
        self.isunusual = QtWidgets.QRadioButton(self.classstartdonetime)
        self.isunusual.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.isunusual.setObjectName("isunusual")
        self.gridLayout_3.addWidget(self.isunusual, 1, 0, 1, 2)
        self.verticalLayout_11.addWidget(self.classstartdonetime)
        self.newAddS = QtWidgets.QPushButton(self.scheduleDiv)
        self.newAddS.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.newAddS.setObjectName("newAddS")
        self.verticalLayout_11.addWidget(self.newAddS)
        self.horizontalLayout_7.addWidget(self.scheduleDiv)
        self.RightSideSchedule = QtWidgets.QFrame(self.scheduletab)
        self.RightSideSchedule.setStyleSheet("QFrame\n"
"{\n"
"    border-radius:10px;\n"
"    padding-top:10px;\n"
"    background:rgb(69, 69, 73);\n"
"}\n"
"QGroupBox{\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    padding-top:0px;\n"
"}\n"
"QComboBox:drop-down{\n"
"    border: 0px;\n"
"    background:rgb(90, 151, 255);\n"
"}\n"
"QComboBox{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}")
        self.RightSideSchedule.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RightSideSchedule.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RightSideSchedule.setObjectName("RightSideSchedule")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.RightSideSchedule)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.topBarS = QtWidgets.QFrame(self.RightSideSchedule)
        self.topBarS.setMaximumSize(QtCore.QSize(16777215, 74))
        self.topBarS.setStyleSheet("QGroupBox{\n"
"    border-radius:3px;\n"
"    background:rgb(77, 135, 255);\n"
"}\n"
"QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"    background:rgb(77, 135, 255);\n"
"}")
        self.topBarS.setObjectName("topBarS")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.topBarS)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.classtimesched = QtWidgets.QGroupBox(self.topBarS)
        self.classtimesched.setMinimumSize(QtCore.QSize(0, 40))
        self.classtimesched.setMaximumSize(QtCore.QSize(100, 16777215))
        self.classtimesched.setTitle("")
        self.classtimesched.setObjectName("classtimesched")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.classtimesched)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.classtimenamesched = QtWidgets.QLabel(self.classtimesched)
        self.classtimenamesched.setMinimumSize(QtCore.QSize(0, 20))
        self.classtimenamesched.setTextFormat(QtCore.Qt.AutoText)
        self.classtimenamesched.setAlignment(QtCore.Qt.AlignCenter)
        self.classtimenamesched.setObjectName("classtimenamesched")
        self.horizontalLayout_37.addWidget(self.classtimenamesched)
        self.horizontalLayout_4.addWidget(self.classtimesched)
        self.classblocksched = QtWidgets.QGroupBox(self.topBarS)
        self.classblocksched.setMinimumSize(QtCore.QSize(0, 40))
        self.classblocksched.setMaximumSize(QtCore.QSize(100, 16777215))
        self.classblocksched.setTitle("")
        self.classblocksched.setObjectName("classblocksched")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.classblocksched)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.classblocknamesched = QtWidgets.QLabel(self.classblocksched)
        self.classblocknamesched.setMinimumSize(QtCore.QSize(0, 20))
        self.classblocknamesched.setAlignment(QtCore.Qt.AlignCenter)
        self.classblocknamesched.setObjectName("classblocknamesched")
        self.horizontalLayout_38.addWidget(self.classblocknamesched)
        self.horizontalLayout_4.addWidget(self.classblocksched)
        self.classnumsched = QtWidgets.QGroupBox(self.topBarS)
        self.classnumsched.setMinimumSize(QtCore.QSize(0, 40))
        self.classnumsched.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.classnumsched.setTitle("")
        self.classnumsched.setObjectName("classnumsched")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.classnumsched)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.classnumnamesched = QtWidgets.QLabel(self.classnumsched)
        self.classnumnamesched.setMinimumSize(QtCore.QSize(0, 20))
        self.classnumnamesched.setAlignment(QtCore.Qt.AlignCenter)
        self.classnumnamesched.setObjectName("classnumnamesched")
        self.horizontalLayout_35.addWidget(self.classnumnamesched)
        self.horizontalLayout_4.addWidget(self.classnumsched)
        self.classsched = QtWidgets.QGroupBox(self.topBarS)
        self.classsched.setMinimumSize(QtCore.QSize(0, 40))
        self.classsched.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.classsched.setTitle("")
        self.classsched.setObjectName("classsched")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.classsched)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.classnamesched = QtWidgets.QLabel(self.classsched)
        self.classnamesched.setMinimumSize(QtCore.QSize(0, 20))
        self.classnamesched.setAlignment(QtCore.Qt.AlignCenter)
        self.classnamesched.setObjectName("classnamesched")
        self.horizontalLayout_34.addWidget(self.classnamesched)
        self.horizontalLayout_4.addWidget(self.classsched)
        self.classinfosched = QtWidgets.QGroupBox(self.topBarS)
        self.classinfosched.setMinimumSize(QtCore.QSize(0, 40))
        self.classinfosched.setMaximumSize(QtCore.QSize(70, 16777215))
        self.classinfosched.setTitle("")
        self.classinfosched.setObjectName("classinfosched")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.classinfosched)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.classinfonamesched = QtWidgets.QLabel(self.classinfosched)
        self.classinfonamesched.setMinimumSize(QtCore.QSize(0, 20))
        self.classinfonamesched.setAlignment(QtCore.Qt.AlignCenter)
        self.classinfonamesched.setObjectName("classinfonamesched")
        self.horizontalLayout_36.addWidget(self.classinfonamesched)
        self.horizontalLayout_4.addWidget(self.classinfosched)
        self.verticalLayout_5.addWidget(self.topBarS)
        self.scrollableClassesDisplay = QtWidgets.QScrollArea(self.RightSideSchedule)
        self.scrollableClassesDisplay.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scrollableClassesDisplay.setStyleSheet("QGroupBox{\n"
"    border-radius:3px;\n"
"    background:rgb(77, 135, 255);\n"
"}\n"
"QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"    background:rgb(77, 135, 255);\n"
"}\n"
"QProgressBar{\n"
"    color:rgb(0, 255, 52);\n"
"}\n"
"QPushButton{\n"
"    border-radius:3px;\n"
"    background:rgb(77, 135, 255);\n"
"}")
        self.scrollableClassesDisplay.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollableClassesDisplay.setWidgetResizable(True)
        self.scrollableClassesDisplay.setObjectName("scrollableClassesDisplay")
        self.sortBy_2 = QtWidgets.QGroupBox(self.RightSideSchedule)
        self.sortBy_2.setStyleSheet("")
        self.sortBy_2.setObjectName("sortBy_2")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.sortBy_2)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.sortDue_2 = QtWidgets.QComboBox(self.sortBy_2)
        self.sortDue_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.sortDue_2.setObjectName("sortDue_2")
        self.sortDue_2.addItem("")
        self.sortDue_2.addItem("")
        self.sortDue_2.addItem("")
        self.horizontalLayout_27.addWidget(self.sortDue_2)
        self.sortAcend_2 = QtWidgets.QComboBox(self.sortBy_2)
        self.sortAcend_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.sortAcend_2.setObjectName("sortAcend_2")
        self.sortAcend_2.addItem("")
        self.sortAcend_2.addItem("")
        self.horizontalLayout_27.addWidget(self.sortAcend_2)
        self.verticalLayout_5.addWidget(self.sortBy_2)
        self.horizontalLayout_7.addWidget(self.RightSideSchedule)
        self.switchTab.addTab(self.scheduletab, "")
        self.horizontalLayout.addWidget(self.switchTab)
        HWTracker.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HWTracker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 967, 22))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuImport_Calendar = QtWidgets.QMenu(self.menuFile)
        self.menuImport_Calendar.setObjectName("menuImport_Calendar")
        self.menuHow_to_use = QtWidgets.QMenu(self.menubar)
        self.menuHow_to_use.setObjectName("menuHow_to_use")
        self.menuAppearence = QtWidgets.QMenu(self.menubar)
        self.menuAppearence.setObjectName("menuAppearence")
        self.menuEnter_Fullscreen = QtWidgets.QMenu(self.menuAppearence)
        self.menuEnter_Fullscreen.setObjectName("menuEnter_Fullscreen")
        self.menuThemes = QtWidgets.QMenu(self.menuAppearence)
        self.menuThemes.setObjectName("menuThemes")
        self.menuDark_Mode_yesss = QtWidgets.QMenu(self.menuThemes)
        self.menuDark_Mode_yesss.setObjectName("menuDark_Mode_yesss")
        self.menuLight_Mode_meh = QtWidgets.QMenu(self.menuThemes)
        self.menuLight_Mode_meh.setObjectName("menuLight_Mode_meh")
        self.menuCustom_2 = QtWidgets.QMenu(self.menuThemes)
        self.menuCustom_2.setObjectName("menuCustom_2")
        self.menuNew = QtWidgets.QMenu(self.menubar)
        self.menuNew.setObjectName("menuNew")
        HWTracker.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HWTracker)
        self.statusbar.setObjectName("statusbar")
        HWTracker.setStatusBar(self.statusbar)
        self.actionAdd_class = QtWidgets.QAction(HWTracker)
        self.actionAdd_class.setObjectName("actionAdd_class")
        self.actionAdd_work = QtWidgets.QAction(HWTracker)
        self.actionAdd_work.setObjectName("actionAdd_work")
        self.actionMake_New = QtWidgets.QAction(HWTracker)
        self.actionMake_New.setObjectName("actionMake_New")
        self.actionExample = QtWidgets.QAction(HWTracker)
        self.actionExample.setObjectName("actionExample")
        self.actionDark_Chocolate = QtWidgets.QAction(HWTracker)
        self.actionDark_Chocolate.setObjectName("actionDark_Chocolate")
        self.actionNight_Sky = QtWidgets.QAction(HWTracker)
        self.actionNight_Sky.setObjectName("actionNight_Sky")
        self.actionChocolate = QtWidgets.QAction(HWTracker)
        self.actionChocolate.setObjectName("actionChocolate")
        self.action500_Shades_Of_Grey = QtWidgets.QAction(HWTracker)
        self.action500_Shades_Of_Grey.setObjectName("action500_Shades_Of_Grey")
        self.actionContrast = QtWidgets.QAction(HWTracker)
        self.actionContrast.setObjectName("actionContrast")
        self.actionNuclear_Explosion = QtWidgets.QAction(HWTracker)
        self.actionNuclear_Explosion.setObjectName("actionNuclear_Explosion")
        self.actionSilk = QtWidgets.QAction(HWTracker)
        self.actionSilk.setObjectName("actionSilk")
        self.actionPaper = QtWidgets.QAction(HWTracker)
        self.actionPaper.setObjectName("actionPaper")
        self.actionMilk = QtWidgets.QAction(HWTracker)
        self.actionMilk.setObjectName("actionMilk")
        self.actionInverse_Contrast = QtWidgets.QAction(HWTracker)
        self.actionInverse_Contrast.setObjectName("actionInverse_Contrast")
        self.actionHow_to_use = QtWidgets.QAction(HWTracker)
        self.actionHow_to_use.setObjectName("actionHow_to_use")
        self.actionSave = QtWidgets.QAction(HWTracker)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_Calendar_As = QtWidgets.QAction(HWTracker)
        self.actionSave_Calendar_As.setObjectName("actionSave_Calendar_As")
        self.actionTodo = QtWidgets.QAction(HWTracker)
        self.actionTodo.setObjectName("actionTodo")
        self.actionClasses = QtWidgets.QAction(HWTracker)
        self.actionClasses.setObjectName("actionClasses")
        self.actiongoogle = QtWidgets.QAction(HWTracker)
        self.actiongoogle.setObjectName("actiongoogle")
        self.actionfile = QtWidgets.QAction(HWTracker)
        self.actionfile.setObjectName("actionfile")
        self.actionAbout = QtWidgets.QAction(HWTracker)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_2 = QtWidgets.QAction(HWTracker)
        self.actionAbout_2.setObjectName("actionAbout_2")
        self.actionType_Here = QtWidgets.QAction(HWTracker)
        self.actionType_Here.setObjectName("actionType_Here")
        self.actionCave = QtWidgets.QAction(HWTracker)
        self.actionCave.setObjectName("actionCave")
        self.actionDark_Chocolate_2 = QtWidgets.QAction(HWTracker)
        self.actionDark_Chocolate_2.setObjectName("actionDark_Chocolate_2")
        self.action51_Shades_Of_Light_Black = QtWidgets.QAction(HWTracker)
        self.action51_Shades_Of_Light_Black.setObjectName("action51_Shades_Of_Light_Black")
        self.actionMooclear_Explosion = QtWidgets.QAction(HWTracker)
        self.actionMooclear_Explosion.setObjectName("actionMooclear_Explosion")
        self.actionMilky = QtWidgets.QAction(HWTracker)
        self.actionMilky.setObjectName("actionMilky")
        self.actionDefault = QtWidgets.QAction(HWTracker)
        self.actionDefault.setObjectName("actionDefault")
        self.actionCreate_Your_Own = QtWidgets.QAction(HWTracker)
        self.actionCreate_Your_Own.setObjectName("actionCreate_Your_Own")
        self.actionExample_2 = QtWidgets.QAction(HWTracker)
        self.actionExample_2.setObjectName("actionExample_2")
        self.actionExit = QtWidgets.QAction(HWTracker)
        self.actionExit.setObjectName("actionExit")
        self.actionEnter_Fullscreen = QtWidgets.QAction(HWTracker)
        self.actionEnter_Fullscreen.setObjectName("actionEnter_Fullscreen")
        self.actionSettings = QtWidgets.QAction(HWTracker)
        self.actionSettings.setObjectName("actionSettings")
        self.actionhomework = QtWidgets.QAction(HWTracker)
        self.actionhomework.setCheckable(True)
        self.actionhomework.setChecked(True)
        self.actionhomework.setObjectName("actionhomework")
        self.actionclass = QtWidgets.QAction(HWTracker)
        self.actionclass.setCheckable(True)
        self.actionclass.setChecked(True)
        self.actionclass.setObjectName("actionclass")
        self.menuSettings.addAction(self.actionAbout_2)
        self.menuSettings.addAction(self.actionSettings)
        self.menuImport_Calendar.addAction(self.actionfile)
        self.menuImport_Calendar.addAction(self.actiongoogle)
        self.menuFile.addAction(self.menuImport_Calendar.menuAction())
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_Calendar_As)
        self.menuEnter_Fullscreen.addAction(self.actionEnter_Fullscreen)
        self.menuEnter_Fullscreen.addAction(self.actionExit)
        self.menuDark_Mode_yesss.addAction(self.actionCave)
        self.menuDark_Mode_yesss.addAction(self.actionDark_Chocolate_2)
        self.menuDark_Mode_yesss.addAction(self.action51_Shades_Of_Light_Black)
        self.menuLight_Mode_meh.addAction(self.actionMooclear_Explosion)
        self.menuLight_Mode_meh.addAction(self.actionMilky)
        self.menuLight_Mode_meh.addAction(self.actionDefault)
        self.menuCustom_2.addAction(self.actionCreate_Your_Own)
        self.menuCustom_2.addAction(self.actionExample_2)
        self.menuThemes.addAction(self.menuDark_Mode_yesss.menuAction())
        self.menuThemes.addAction(self.menuLight_Mode_meh.menuAction())
        self.menuThemes.addSeparator()
        self.menuThemes.addAction(self.menuCustom_2.menuAction())
        self.menuAppearence.addAction(self.menuEnter_Fullscreen.menuAction())
        self.menuAppearence.addAction(self.menuThemes.menuAction())
        self.menuAppearence.addAction(self.actionAbout)
        self.menuNew.addAction(self.actionhomework)
        self.menuNew.addAction(self.actionclass)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuNew.menuAction())
        self.menubar.addAction(self.menuAppearence.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHow_to_use.menuAction())

        self.retranslateUi(HWTracker)
        self.switchTab.setCurrentIndex(0)
        self.actionEnter_Fullscreen.triggered.connect(HWTracker.showFullScreen)
        self.actionExit.triggered.connect(HWTracker.showNormal)
        self.actionclass.triggered['bool'].connect(self.todoDiv.setVisible)
        self.actionhomework.triggered['bool'].connect(self.scheduleDiv.setVisible)
        QtCore.QMetaObject.connectSlotsByName(HWTracker)

    def retranslateUi(self, HWTracker):
        _translate = QtCore.QCoreApplication.translate
        HWTracker.setWindowTitle(_translate("HWTracker", "HWTracker V1.0"))
        self.newHomeworkGroup.setTitle(_translate("HWTracker", "Homework"))
        self.newHWText.setHtml(_translate("HWTracker", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.newHWText.setPlaceholderText(_translate("HWTracker", "Describe your homework... Does it fly? Is it blue? etc "))
        self.newDueGroup.setTitle(_translate("HWTracker", "Due Date"))
        self.radioButton.setText(_translate("HWTracker", "Assignment Repeats?"))
        self.newDifficultyGroup.setTitle(_translate("HWTracker", "Difficulty"))
        self.newClassGroup.setTitle(_translate("HWTracker", "Class"))
        self.newClassToHW.setItemText(0, _translate("HWTracker", "Comp Sci "))
        self.newAdd.setText(_translate("HWTracker", "Add"))
        self.donenametodo.setText(_translate("HWTracker", "Done?"))
        self.blocknametodo.setText(_translate("HWTracker", "Block"))
        self.classnametodo.setText(_translate("HWTracker", "Class"))
        self.diffratingtodo.setText(_translate("HWTracker", "Difficulty"))
        self.progressbartodo.setText(_translate("HWTracker", "Progress"))
        self.dueinnametodo.setText(_translate("HWTracker", "Due"))
        self.infonametodo.setText(_translate("HWTracker", "Info"))
        self.sortBy.setTitle(_translate("HWTracker", "Sort By:"))
        self.sortDue.setItemText(0, _translate("HWTracker", "Due Date"))
        self.sortDue.setItemText(1, _translate("HWTracker", "Class"))
        self.sortDue.setItemText(2, _translate("HWTracker", "Difficulty"))
        self.sortAcend.setItemText(0, _translate("HWTracker", "Ascending (A-Z, 1-10)"))
        self.sortAcend.setItemText(1, _translate("HWTracker", "Decending (Z-A, 10-1)"))
        self.sortShowDone.setText(_translate("HWTracker", "Show done"))
        self.switchTab.setTabText(self.switchTab.indexOf(self.todotab), _translate("HWTracker", "Todo List"))
        self.NewClassGroup.setTitle(_translate("HWTracker", "Description"))
        self.newClassroomNum.setPlaceholderText(_translate("HWTracker", "Classroom number"))
        self.newClassName_2.setHtml(_translate("HWTracker", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.newClassName_2.setPlaceholderText(_translate("HWTracker", "Class Name"))
        self.newClassDesc.setHtml(_translate("HWTracker", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.newClassDesc.setPlaceholderText(_translate("HWTracker", "Describe your class... Does it eat? Is it pink? etc "))
        self.newBlock.setPlaceholderText(_translate("HWTracker", "Block"))
        self.classstartdonetime.setTitle(_translate("HWTracker", "Time Starts        Time Ends"))
        self.isunusual.setText(_translate("HWTracker", "Custom (swap schedule)"))
        self.newAddS.setText(_translate("HWTracker", "Add"))
        self.classtimenamesched.setText(_translate("HWTracker", "Time"))
        self.classblocknamesched.setText(_translate("HWTracker", "Block"))
        self.classnumnamesched.setText(_translate("HWTracker", "Classroom #"))
        self.classnamesched.setText(_translate("HWTracker", "Class"))
        self.classinfonamesched.setText(_translate("HWTracker", "Info"))
        self.sortBy_2.setTitle(_translate("HWTracker", "Sort By:"))
        self.sortDue_2.setItemText(0, _translate("HWTracker", "Time"))
        self.sortDue_2.setItemText(1, _translate("HWTracker", "Class"))
        self.sortDue_2.setItemText(2, _translate("HWTracker", "Block"))
        self.sortAcend_2.setItemText(0, _translate("HWTracker", "Ascending (A-Z, 1-10)"))
        self.sortAcend_2.setItemText(1, _translate("HWTracker", "Decending (Z-A, 10-1)"))
        self.switchTab.setTabText(self.switchTab.indexOf(self.scheduletab), _translate("HWTracker", "Schedule"))
        self.menuSettings.setTitle(_translate("HWTracker", "Options"))
        self.menuFile.setTitle(_translate("HWTracker", "File"))
        self.menuImport_Calendar.setTitle(_translate("HWTracker", "Import Calendar"))
        self.menuHow_to_use.setTitle(_translate("HWTracker", "How to use"))
        self.menuAppearence.setTitle(_translate("HWTracker", "Appearance"))
        self.menuEnter_Fullscreen.setTitle(_translate("HWTracker", "Fullscreen"))
        self.menuThemes.setTitle(_translate("HWTracker", "Themes"))
        self.menuDark_Mode_yesss.setTitle(_translate("HWTracker", "Dark Mode (yesss)"))
        self.menuLight_Mode_meh.setTitle(_translate("HWTracker", "Light Mode (meh)"))
        self.menuCustom_2.setTitle(_translate("HWTracker", "Custom"))
        self.menuNew.setTitle(_translate("HWTracker", "Sidebars"))
        self.actionAdd_class.setText(_translate("HWTracker", "Add class"))
        self.actionAdd_work.setText(_translate("HWTracker", "Add work"))
        self.actionMake_New.setText(_translate("HWTracker", "Make New"))
        self.actionExample.setText(_translate("HWTracker", "Example"))
        self.actionDark_Chocolate.setText(_translate("HWTracker", "Cave"))
        self.actionNight_Sky.setText(_translate("HWTracker", "Night Sky"))
        self.actionChocolate.setText(_translate("HWTracker", "Dark Chocolate"))
        self.action500_Shades_Of_Grey.setText(_translate("HWTracker", "51 Shades Of Grey"))
        self.actionContrast.setText(_translate("HWTracker", "Contrast"))
        self.actionNuclear_Explosion.setText(_translate("HWTracker", "Nuclear Explosion"))
        self.actionSilk.setText(_translate("HWTracker", "Cloud"))
        self.actionPaper.setText(_translate("HWTracker", "Paper"))
        self.actionMilk.setText(_translate("HWTracker", "Milk (Default)"))
        self.actionInverse_Contrast.setText(_translate("HWTracker", "Inverse Contrast"))
        self.actionHow_to_use.setText(_translate("HWTracker", "How to use"))
        self.actionSave.setText(_translate("HWTracker", "Save Calendar"))
        self.actionSave_Calendar_As.setText(_translate("HWTracker", "Save Calendar As"))
        self.actionTodo.setText(_translate("HWTracker", "Todo"))
        self.actionClasses.setText(_translate("HWTracker", "Classes"))
        self.actiongoogle.setText(_translate("HWTracker", "google"))
        self.actionfile.setText(_translate("HWTracker", "file"))
        self.actionAbout.setText(_translate("HWTracker", "Help"))
        self.actionAbout_2.setText(_translate("HWTracker", "About"))
        self.actionType_Here.setText(_translate("HWTracker", "Type Here"))
        self.actionCave.setText(_translate("HWTracker", "Blue Cave (default)"))
        self.actionDark_Chocolate_2.setText(_translate("HWTracker", "Dark Chocolate"))
        self.action51_Shades_Of_Light_Black.setText(_translate("HWTracker", "51 Shades Of Light Black"))
        self.actionMooclear_Explosion.setText(_translate("HWTracker", "Mooclear Explosion"))
        self.actionMilky.setText(_translate("HWTracker", "Cloud"))
        self.actionDefault.setText(_translate("HWTracker", "Milky"))
        self.actionCreate_Your_Own.setText(_translate("HWTracker", "Create Your Own"))
        self.actionExample_2.setText(_translate("HWTracker", "Example"))
        self.actionExit.setText(_translate("HWTracker", "Exit Fullscreen"))
        self.actionExit.setShortcut(_translate("HWTracker", "Ctrl+F12"))
        self.actionEnter_Fullscreen.setText(_translate("HWTracker", "Enter Fullscreen"))
        self.actionEnter_Fullscreen.setShortcut(_translate("HWTracker", "Ctrl+F11"))
        self.actionSettings.setText(_translate("HWTracker", "Settings"))
        self.actionhomework.setText(_translate("HWTracker", "homework"))
        self.actionclass.setText(_translate("HWTracker", "class"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HWTracker = QtWidgets.QMainWindow()
    ui = Ui_HWTracker()
    ui.setupUi(HWTracker)
    HWTracker.show()
    sys.exit(app.exec_())
