# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appaswidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(963, 682)
        self.switchTab = QtWidgets.QTabWidget(Form)
        self.switchTab.setGeometry(QtCore.QRect(10, 10, 943, 663))
        self.switchTab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.switchTab.setObjectName("switchTab")
        self.todotab = QtWidgets.QWidget()
        self.todotab.setObjectName("todotab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.todotab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.todoDiv = QtWidgets.QGroupBox(self.todotab)
        self.todoDiv.setMaximumSize(QtCore.QSize(225, 16777215))
        self.todoDiv.setTitle("")
        self.todoDiv.setObjectName("todoDiv")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.todoDiv)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.newHomeworkGroup = QtWidgets.QGroupBox(self.todoDiv)
        self.newHomeworkGroup.setObjectName("newHomeworkGroup")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.newHomeworkGroup)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.newHWText = QtWidgets.QTextEdit(self.newHomeworkGroup)
        self.newHWText.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.newHWText.setStyleSheet("")
        self.newHWText.setObjectName("newHWText")
        self.verticalLayout_13.addWidget(self.newHWText)
        self.verticalLayout_14.addWidget(self.newHomeworkGroup)
        self.newDueGroup = QtWidgets.QGroupBox(self.todoDiv)
        self.newDueGroup.setObjectName("newDueGroup")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.newDueGroup)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.newDueTime = QtWidgets.QDateTimeEdit(self.newDueGroup)
        self.newDueTime.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.newDueTime.setObjectName("newDueTime")
        self.verticalLayout_6.addWidget(self.newDueTime)
        self.radioButton = QtWidgets.QRadioButton(self.newDueGroup)
        self.radioButton.setStyleSheet("")
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_6.addWidget(self.radioButton)
        self.verticalLayout_14.addWidget(self.newDueGroup)
        self.newDifficultyGroup = QtWidgets.QGroupBox(self.todoDiv)
        self.newDifficultyGroup.setObjectName("newDifficultyGroup")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.newDifficultyGroup)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.newDifficultySlider = QtWidgets.QSlider(self.newDifficultyGroup)
        self.newDifficultySlider.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.newDifficultySlider.setStyleSheet("")
        self.newDifficultySlider.setMaximum(10)
        self.newDifficultySlider.setOrientation(QtCore.Qt.Horizontal)
        self.newDifficultySlider.setObjectName("newDifficultySlider")
        self.verticalLayout_4.addWidget(self.newDifficultySlider)
        self.verticalLayout_14.addWidget(self.newDifficultyGroup)
        self.newClassGroup = QtWidgets.QGroupBox(self.todoDiv)
        self.newClassGroup.setObjectName("newClassGroup")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.newClassGroup)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.newClassToHW = QtWidgets.QComboBox(self.newClassGroup)
        self.newClassToHW.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.newClassToHW.setObjectName("newClassToHW")
        self.newClassToHW.addItem("")
        self.verticalLayout_12.addWidget(self.newClassToHW)
        self.verticalLayout_14.addWidget(self.newClassGroup)
        self.newAdd = QtWidgets.QPushButton(self.todoDiv)
        self.newAdd.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.newAdd.setObjectName("newAdd")
        self.verticalLayout_14.addWidget(self.newAdd)
        self.horizontalLayout_2.addWidget(self.todoDiv)
        self.RightSideTodo = QtWidgets.QFrame(self.todotab)
        self.RightSideTodo.setStyleSheet("QFrame\n"
"{\n"
"    border-radius:10px;\n"
"    padding-top:10px;\n"
"    background:rgb(69, 69, 73);\n"
"}\n"
"QGroupBox{\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    padding-top:0px;\n"
"}\n"
"QRadioButton{\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius:3px;\n"
"}\n"
"QComboBox{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox:drop-down{\n"
"    border: 0px;\n"
"    background:rgb(90, 151, 255);\n"
"}\n"
"QComboBox:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}\n"
"QRadioButton:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}")
        self.RightSideTodo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RightSideTodo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RightSideTodo.setObjectName("RightSideTodo")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.RightSideTodo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topbar = QtWidgets.QFrame(self.RightSideTodo)
        self.topbar.setStyleSheet("QGroupBox{\n"
"    border-radius:3px;\n"
"    background:rgb(77, 135, 255);\n"
"}\n"
"QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"    background:rgb(77, 135, 255);\n"
"}")
        self.topbar.setObjectName("topbar")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout(self.topbar)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.donetodo = QtWidgets.QGroupBox(self.topbar)
        self.donetodo.setMaximumSize(QtCore.QSize(69, 47))
        self.donetodo.setTitle("")
        self.donetodo.setObjectName("donetodo")
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout(self.donetodo)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.donenametodo = QtWidgets.QLabel(self.donetodo)
        self.donenametodo.setAlignment(QtCore.Qt.AlignCenter)
        self.donenametodo.setObjectName("donenametodo")
        self.horizontalLayout_44.addWidget(self.donenametodo)
        self.horizontalLayout_46.addWidget(self.donetodo)
        self.blocktodo = QtWidgets.QGroupBox(self.topbar)
        self.blocktodo.setMaximumSize(QtCore.QSize(64, 47))
        self.blocktodo.setTitle("")
        self.blocktodo.setObjectName("blocktodo")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.blocktodo)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.blocknametodo = QtWidgets.QLabel(self.blocktodo)
        self.blocknametodo.setAlignment(QtCore.Qt.AlignCenter)
        self.blocknametodo.setObjectName("blocknametodo")
        self.horizontalLayout_41.addWidget(self.blocknametodo)
        self.horizontalLayout_46.addWidget(self.blocktodo)
        self.classinsidetodo = QtWidgets.QGroupBox(self.topbar)
        self.classinsidetodo.setTitle("")
        self.classinsidetodo.setObjectName("classinsidetodo")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.classinsidetodo)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.classnametodo = QtWidgets.QLabel(self.classinsidetodo)
        self.classnametodo.setAlignment(QtCore.Qt.AlignCenter)
        self.classnametodo.setObjectName("classnametodo")
        self.horizontalLayout_40.addWidget(self.classnametodo)
        self.horizontalLayout_46.addWidget(self.classinsidetodo)
        self.difftodo = QtWidgets.QGroupBox(self.topbar)
        self.difftodo.setMaximumSize(QtCore.QSize(86, 47))
        self.difftodo.setTitle("")
        self.difftodo.setObjectName("difftodo")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.difftodo)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.diffratingtodo = QtWidgets.QLabel(self.difftodo)
        self.diffratingtodo.setAlignment(QtCore.Qt.AlignCenter)
        self.diffratingtodo.setObjectName("diffratingtodo")
        self.horizontalLayout_43.addWidget(self.diffratingtodo)
        self.horizontalLayout_46.addWidget(self.difftodo)
        self.progresstodo = QtWidgets.QGroupBox(self.topbar)
        self.progresstodo.setMaximumSize(QtCore.QSize(85, 47))
        self.progresstodo.setTitle("")
        self.progresstodo.setObjectName("progresstodo")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.progresstodo)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.progressbartodo = QtWidgets.QLabel(self.progresstodo)
        self.progressbartodo.setAlignment(QtCore.Qt.AlignCenter)
        self.progressbartodo.setObjectName("progressbartodo")
        self.horizontalLayout_8.addWidget(self.progressbartodo)
        self.horizontalLayout_46.addWidget(self.progresstodo)
        self.dueintodo = QtWidgets.QGroupBox(self.topbar)
        self.dueintodo.setMaximumSize(QtCore.QSize(55, 47))
        self.dueintodo.setTitle("")
        self.dueintodo.setObjectName("dueintodo")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.dueintodo)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.dueinnametodo = QtWidgets.QLabel(self.dueintodo)
        self.dueinnametodo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dueinnametodo.setAlignment(QtCore.Qt.AlignCenter)
        self.dueinnametodo.setObjectName("dueinnametodo")
        self.horizontalLayout_42.addWidget(self.dueinnametodo)
        self.horizontalLayout_46.addWidget(self.dueintodo)
        self.infotodo = QtWidgets.QGroupBox(self.topbar)
        self.infotodo.setMaximumSize(QtCore.QSize(70, 71))
        self.infotodo.setTitle("")
        self.infotodo.setObjectName("infotodo")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout(self.infotodo)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.infonametodo = QtWidgets.QLabel(self.infotodo)
        self.infonametodo.setAlignment(QtCore.Qt.AlignCenter)
        self.infonametodo.setObjectName("infonametodo")
        self.horizontalLayout_45.addWidget(self.infonametodo)
        self.horizontalLayout_46.addWidget(self.infotodo)
        self.verticalLayout.addWidget(self.topbar)
        self.scrollableHomeworkDisplay = QtWidgets.QScrollArea(self.RightSideTodo)
        self.scrollableHomeworkDisplay.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scrollableHomeworkDisplay.setStyleSheet("QGroupBox{\n"
"    border-radius:3px;\n"
"    background:rgb(77, 135, 255);\n"
"}\n"
"QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"    background:rgb(77, 135, 255);\n"
"}\n"
"QProgressBar{\n"
"    color:rgb(0, 255, 52);\n"
"}\n"
"QPushButton{\n"
"    border-radius:3px;\n"
"    background:rgb(77, 135, 255);\n"
"}")
        self.scrollableHomeworkDisplay.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollableHomeworkDisplay.setWidgetResizable(True)
        self.scrollableHomeworkDisplay.setObjectName("scrollableHomeworkDisplay")
        self.scrollHomework = QtWidgets.QWidget()
        self.scrollHomework.setGeometry(QtCore.QRect(0, 0, 632, 405))
        self.scrollHomework.setObjectName("scrollHomework")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollHomework)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.classSubject = QtWidgets.QFrame(self.scrollHomework)
        self.classSubject.setMinimumSize(QtCore.QSize(600, 72))
        self.classSubject.setMaximumSize(QtCore.QSize(16777215, 72))
        self.classSubject.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.classSubject.setFrameShadow(QtWidgets.QFrame.Raised)
        self.classSubject.setObjectName("classSubject")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.classSubject)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.ifDone = QtWidgets.QCheckBox(self.classSubject)
        self.ifDone.setMaximumSize(QtCore.QSize(20, 16777215))
        self.ifDone.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.ifDone.setText("")
        self.ifDone.setObjectName("ifDone")
        self.horizontalLayout_14.addWidget(self.ifDone)
        self.block = QtWidgets.QGroupBox(self.classSubject)
        self.block.setMaximumSize(QtCore.QSize(39, 16777215))
        self.block.setTitle("")
        self.block.setObjectName("block")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.block)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.blockName = QtWidgets.QLabel(self.block)
        self.blockName.setAlignment(QtCore.Qt.AlignCenter)
        self.blockName.setObjectName("blockName")
        self.horizontalLayout_11.addWidget(self.blockName)
        self.horizontalLayout_14.addWidget(self.block)
        self.classinside = QtWidgets.QGroupBox(self.classSubject)
        self.classinside.setTitle("")
        self.classinside.setObjectName("classinside")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.classinside)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.classname = QtWidgets.QLabel(self.classinside)
        self.classname.setAlignment(QtCore.Qt.AlignCenter)
        self.classname.setObjectName("classname")
        self.horizontalLayout_10.addWidget(self.classname)
        self.horizontalLayout_14.addWidget(self.classinside)
        self.diff = QtWidgets.QGroupBox(self.classSubject)
        self.diff.setMaximumSize(QtCore.QSize(57, 16777215))
        self.diff.setTitle("")
        self.diff.setObjectName("diff")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.diff)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.diffrating = QtWidgets.QLabel(self.diff)
        self.diffrating.setAlignment(QtCore.Qt.AlignCenter)
        self.diffrating.setObjectName("diffrating")
        self.horizontalLayout_9.addWidget(self.diffrating)
        self.horizontalLayout_14.addWidget(self.diff)
        self.progress = QtWidgets.QGroupBox(self.classSubject)
        self.progress.setMaximumSize(QtCore.QSize(50, 71))
        self.progress.setTitle("")
        self.progress.setObjectName("progress")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.progress)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.progressBar = QtWidgets.QProgressBar(self.progress)
        self.progressBar.setMaximumSize(QtCore.QSize(95, 16777215))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background:rgb(255, 255, 255);\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_12.addWidget(self.progressBar)
        self.horizontalLayout_14.addWidget(self.progress)
        self.duein = QtWidgets.QGroupBox(self.classSubject)
        self.duein.setMaximumSize(QtCore.QSize(50, 71))
        self.duein.setTitle("")
        self.duein.setObjectName("duein")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.duein)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.dueinName = QtWidgets.QLabel(self.duein)
        self.dueinName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dueinName.setAlignment(QtCore.Qt.AlignCenter)
        self.dueinName.setObjectName("dueinName")
        self.horizontalLayout_13.addWidget(self.dueinName)
        self.horizontalLayout_14.addWidget(self.duein)
        self.extrainfo = QtWidgets.QFrame(self.classSubject)
        self.extrainfo.setMaximumSize(QtCore.QSize(51, 16777215))
        self.extrainfo.setObjectName("extrainfo")
        self.extrabtn = QtWidgets.QPushButton(self.extrainfo)
        self.extrabtn.setGeometry(QtCore.QRect(0, 0, 40, 38))
        self.extrabtn.setMinimumSize(QtCore.QSize(40, 38))
        self.extrabtn.setMaximumSize(QtCore.QSize(40, 38))
        self.extrabtn.setObjectName("extrabtn")
        self.horizontalLayout_14.addWidget(self.extrainfo)
        self.verticalLayout_2.addWidget(self.classSubject)
        self.scrollableHomeworkDisplay.setWidget(self.scrollHomework)
        self.verticalLayout.addWidget(self.scrollableHomeworkDisplay)
        self.sortBy = QtWidgets.QGroupBox(self.RightSideTodo)
        self.sortBy.setObjectName("sortBy")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.sortBy)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sortDue = QtWidgets.QComboBox(self.sortBy)
        self.sortDue.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.sortDue.setObjectName("sortDue")
        self.sortDue.addItem("")
        self.sortDue.addItem("")
        self.sortDue.addItem("")
        self.horizontalLayout_3.addWidget(self.sortDue)
        self.sortAcend = QtWidgets.QComboBox(self.sortBy)
        self.sortAcend.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.sortAcend.setObjectName("sortAcend")
        self.sortAcend.addItem("")
        self.sortAcend.addItem("")
        self.horizontalLayout_3.addWidget(self.sortAcend)
        self.sortShowDone = QtWidgets.QRadioButton(self.sortBy)
        self.sortShowDone.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sortShowDone.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.sortShowDone.setObjectName("sortShowDone")
        self.horizontalLayout_3.addWidget(self.sortShowDone)
        self.verticalLayout.addWidget(self.sortBy)
        self.horizontalLayout_2.addWidget(self.RightSideTodo)
        self.switchTab.addTab(self.todotab, "")
        self.scheduletab = QtWidgets.QWidget()
        self.scheduletab.setObjectName("scheduletab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.scheduletab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.scheduleDiv = QtWidgets.QGroupBox(self.scheduletab)
        self.scheduleDiv.setMaximumSize(QtCore.QSize(225, 16777215))
        self.scheduleDiv.setStyleSheet("QGroupBox{\n"
"    border-radius:10px;\n"
"    padding-top:10px;\n"
"    background:rgb(69, 69, 73);\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"QRadioButton{\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius:3px;\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:3px;\n"
"    border: 1px solid rgb(28, 139, 255);\n"
"}\n"
"QTextEdit{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QDateTimeEdit:drop-down{\n"
"    border: 0px;\n"
"    background:rgb(90, 151, 255);\n"
"}\n"
"QDateTimeEdit{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QDateTimeEdit:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}\n"
"QTextEdit:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}\n"
"QRadioButton:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}")
        self.scheduleDiv.setTitle("")
        self.scheduleDiv.setObjectName("scheduleDiv")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.scheduleDiv)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.NewClassGroup = QtWidgets.QGroupBox(self.scheduleDiv)
        self.NewClassGroup.setObjectName("NewClassGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.NewClassGroup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.newClassroomNum = QtWidgets.QTextEdit(self.NewClassGroup)
        self.newClassroomNum.setMaximumSize(QtCore.QSize(141, 30))
        self.newClassroomNum.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.newClassroomNum.setObjectName("newClassroomNum")
        self.gridLayout_2.addWidget(self.newClassroomNum, 2, 1, 1, 1)
        self.newClassName_2 = QtWidgets.QTextEdit(self.NewClassGroup)
        self.newClassName_2.setMaximumSize(QtCore.QSize(180, 60))
        self.newClassName_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.newClassName_2.setObjectName("newClassName_2")
        self.gridLayout_2.addWidget(self.newClassName_2, 0, 0, 1, 2)
        self.newClassDesc = QtWidgets.QTextEdit(self.NewClassGroup)
        self.newClassDesc.setMaximumSize(QtCore.QSize(180, 16777215))
        self.newClassDesc.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.newClassDesc.setObjectName("newClassDesc")
        self.gridLayout_2.addWidget(self.newClassDesc, 1, 0, 1, 2)
        self.newBlock = QtWidgets.QTextEdit(self.NewClassGroup)
        self.newBlock.setMaximumSize(QtCore.QSize(50, 30))
        self.newBlock.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.newBlock.setObjectName("newBlock")
        self.gridLayout_2.addWidget(self.newBlock, 2, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.NewClassGroup)
        self.classstartdonetime = QtWidgets.QGroupBox(self.scheduleDiv)
        self.classstartdonetime.setObjectName("classstartdonetime")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.classstartdonetime)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.starts = QtWidgets.QTimeEdit(self.classstartdonetime)
        self.starts.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.starts.setObjectName("starts")
        self.gridLayout_3.addWidget(self.starts, 0, 0, 1, 1)
        self.done = QtWidgets.QTimeEdit(self.classstartdonetime)
        self.done.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.done.setObjectName("done")
        self.gridLayout_3.addWidget(self.done, 0, 1, 1, 1)
        self.isunusual = QtWidgets.QRadioButton(self.classstartdonetime)
        self.isunusual.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.isunusual.setObjectName("isunusual")
        self.gridLayout_3.addWidget(self.isunusual, 1, 0, 1, 2)
        self.verticalLayout_11.addWidget(self.classstartdonetime)
        self.newAddS = QtWidgets.QPushButton(self.scheduleDiv)
        self.newAddS.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.newAddS.setObjectName("newAddS")
        self.verticalLayout_11.addWidget(self.newAddS)
        self.horizontalLayout_7.addWidget(self.scheduleDiv)
        self.RightSideSchedule = QtWidgets.QFrame(self.scheduletab)
        self.RightSideSchedule.setStyleSheet("QFrame\n"
"{\n"
"    border-radius:10px;\n"
"    padding-top:10px;\n"
"    background:rgb(69, 69, 73);\n"
"}\n"
"QGroupBox{\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    padding-top:0px;\n"
"}\n"
"QComboBox:drop-down{\n"
"    border: 0px;\n"
"    background:rgb(90, 151, 255);\n"
"}\n"
"QComboBox{\n"
"    border-radius: 3px;\n"
"    border: 1px solid rgb(27, 129, 255);\n"
"    background: rgb(50, 50, 54);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox:hover{\n"
"    border:1px solid rgb(255, 247, 118);\n"
"}")
        self.RightSideSchedule.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RightSideSchedule.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RightSideSchedule.setObjectName("RightSideSchedule")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.RightSideSchedule)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.topBarS = QtWidgets.QFrame(self.RightSideSchedule)
        self.topBarS.setMaximumSize(QtCore.QSize(16777215, 74))
        self.topBarS.setStyleSheet("QGroupBox{\n"
"    border-radius:3px;\n"
"    background:rgb(77, 135, 255);\n"
"}\n"
"QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"    background:rgb(77, 135, 255);\n"
"}")
        self.topBarS.setObjectName("topBarS")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.topBarS)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.classtimesched = QtWidgets.QGroupBox(self.topBarS)
        self.classtimesched.setMinimumSize(QtCore.QSize(0, 40))
        self.classtimesched.setMaximumSize(QtCore.QSize(100, 16777215))
        self.classtimesched.setTitle("")
        self.classtimesched.setObjectName("classtimesched")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.classtimesched)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.classtimenamesched = QtWidgets.QLabel(self.classtimesched)
        self.classtimenamesched.setMinimumSize(QtCore.QSize(0, 20))
        self.classtimenamesched.setTextFormat(QtCore.Qt.AutoText)
        self.classtimenamesched.setAlignment(QtCore.Qt.AlignCenter)
        self.classtimenamesched.setObjectName("classtimenamesched")
        self.horizontalLayout_37.addWidget(self.classtimenamesched)
        self.horizontalLayout_4.addWidget(self.classtimesched)
        self.classblocksched = QtWidgets.QGroupBox(self.topBarS)
        self.classblocksched.setMinimumSize(QtCore.QSize(0, 40))
        self.classblocksched.setMaximumSize(QtCore.QSize(100, 16777215))
        self.classblocksched.setTitle("")
        self.classblocksched.setObjectName("classblocksched")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.classblocksched)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.classblocknamesched = QtWidgets.QLabel(self.classblocksched)
        self.classblocknamesched.setMinimumSize(QtCore.QSize(0, 20))
        self.classblocknamesched.setAlignment(QtCore.Qt.AlignCenter)
        self.classblocknamesched.setObjectName("classblocknamesched")
        self.horizontalLayout_38.addWidget(self.classblocknamesched)
        self.horizontalLayout_4.addWidget(self.classblocksched)
        self.classnumsched = QtWidgets.QGroupBox(self.topBarS)
        self.classnumsched.setMinimumSize(QtCore.QSize(0, 40))
        self.classnumsched.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.classnumsched.setTitle("")
        self.classnumsched.setObjectName("classnumsched")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.classnumsched)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.classnumnamesched = QtWidgets.QLabel(self.classnumsched)
        self.classnumnamesched.setMinimumSize(QtCore.QSize(0, 20))
        self.classnumnamesched.setAlignment(QtCore.Qt.AlignCenter)
        self.classnumnamesched.setObjectName("classnumnamesched")
        self.horizontalLayout_35.addWidget(self.classnumnamesched)
        self.horizontalLayout_4.addWidget(self.classnumsched)
        self.classsched = QtWidgets.QGroupBox(self.topBarS)
        self.classsched.setMinimumSize(QtCore.QSize(0, 40))
        self.classsched.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.classsched.setTitle("")
        self.classsched.setObjectName("classsched")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.classsched)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.classnamesched = QtWidgets.QLabel(self.classsched)
        self.classnamesched.setMinimumSize(QtCore.QSize(0, 20))
        self.classnamesched.setAlignment(QtCore.Qt.AlignCenter)
        self.classnamesched.setObjectName("classnamesched")
        self.horizontalLayout_34.addWidget(self.classnamesched)
        self.horizontalLayout_4.addWidget(self.classsched)
        self.classinfosched = QtWidgets.QGroupBox(self.topBarS)
        self.classinfosched.setMinimumSize(QtCore.QSize(0, 40))
        self.classinfosched.setMaximumSize(QtCore.QSize(70, 16777215))
        self.classinfosched.setTitle("")
        self.classinfosched.setObjectName("classinfosched")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.classinfosched)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.classinfonamesched = QtWidgets.QLabel(self.classinfosched)
        self.classinfonamesched.setMinimumSize(QtCore.QSize(0, 20))
        self.classinfonamesched.setAlignment(QtCore.Qt.AlignCenter)
        self.classinfonamesched.setObjectName("classinfonamesched")
        self.horizontalLayout_36.addWidget(self.classinfonamesched)
        self.horizontalLayout_4.addWidget(self.classinfosched)
        self.verticalLayout_5.addWidget(self.topBarS)
        self.scrollableClassesDisplay = QtWidgets.QScrollArea(self.RightSideSchedule)
        self.scrollableClassesDisplay.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scrollableClassesDisplay.setStyleSheet("QGroupBox{\n"
"    border-radius:3px;\n"
"    background:rgb(77, 135, 255);\n"
"}\n"
"QLabel{\n"
"    color:rgb(255, 255, 255);\n"
"    background:rgb(77, 135, 255);\n"
"}\n"
"QProgressBar{\n"
"    color:rgb(0, 255, 52);\n"
"}\n"
"QPushButton{\n"
"    border-radius:3px;\n"
"    background:rgb(77, 135, 255);\n"
"}")
        self.scrollableClassesDisplay.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollableClassesDisplay.setWidgetResizable(True)
        self.scrollableClassesDisplay.setObjectName("scrollableClassesDisplay")
        self.scrollClass = QtWidgets.QWidget()
        self.scrollClass.setGeometry(QtCore.QRect(0, 0, 632, 405))
        self.scrollClass.setObjectName("scrollClass")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollClass)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.classItem = QtWidgets.QFrame(self.scrollClass)
        self.classItem.setMinimumSize(QtCore.QSize(600, 71))
        self.classItem.setMaximumSize(QtCore.QSize(16777215, 71))
        self.classItem.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.classItem.setFrameShadow(QtWidgets.QFrame.Raised)
        self.classItem.setObjectName("classItem")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.classItem)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.timeclassstartend = QtWidgets.QGroupBox(self.classItem)
        self.timeclassstartend.setMaximumSize(QtCore.QSize(100, 71))
        self.timeclassstartend.setTitle("")
        self.timeclassstartend.setObjectName("timeclassstartend")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.timeclassstartend)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.time = QtWidgets.QLabel(self.timeclassstartend)
        self.time.setMinimumSize(QtCore.QSize(0, 20))
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.horizontalLayout_33.addWidget(self.time)
        self.horizontalLayout_16.addWidget(self.timeclassstartend)
        self.classBlockSched = QtWidgets.QGroupBox(self.classItem)
        self.classBlockSched.setMaximumSize(QtCore.QSize(50, 71))
        self.classBlockSched.setTitle("")
        self.classBlockSched.setObjectName("classBlockSched")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.classBlockSched)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.classBlockTextSched = QtWidgets.QLabel(self.classBlockSched)
        self.classBlockTextSched.setMinimumSize(QtCore.QSize(0, 20))
        self.classBlockTextSched.setAlignment(QtCore.Qt.AlignCenter)
        self.classBlockTextSched.setObjectName("classBlockTextSched")
        self.horizontalLayout_29.addWidget(self.classBlockTextSched)
        self.horizontalLayout_16.addWidget(self.classBlockSched)
        self.classNumberSched = QtWidgets.QGroupBox(self.classItem)
        self.classNumberSched.setTitle("")
        self.classNumberSched.setObjectName("classNumberSched")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.classNumberSched)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.classNumberNameSched = QtWidgets.QLabel(self.classNumberSched)
        self.classNumberNameSched.setMinimumSize(QtCore.QSize(0, 20))
        self.classNumberNameSched.setAlignment(QtCore.Qt.AlignCenter)
        self.classNumberNameSched.setObjectName("classNumberNameSched")
        self.horizontalLayout_30.addWidget(self.classNumberNameSched)
        self.horizontalLayout_16.addWidget(self.classNumberSched)
        self.classNameSched_2 = QtWidgets.QGroupBox(self.classItem)
        self.classNameSched_2.setTitle("")
        self.classNameSched_2.setObjectName("classNameSched_2")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.classNameSched_2)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.classNameSched = QtWidgets.QLabel(self.classNameSched_2)
        self.classNameSched.setMinimumSize(QtCore.QSize(0, 20))
        self.classNameSched.setAlignment(QtCore.Qt.AlignCenter)
        self.classNameSched.setObjectName("classNameSched")
        self.horizontalLayout_31.addWidget(self.classNameSched)
        self.horizontalLayout_16.addWidget(self.classNameSched_2)
        self.showExtra = QtWidgets.QPushButton(self.classItem)
        self.showExtra.setMinimumSize(QtCore.QSize(40, 38))
        self.showExtra.setMaximumSize(QtCore.QSize(40, 38))
        self.showExtra.setObjectName("showExtra")
        self.horizontalLayout_16.addWidget(self.showExtra)
        self.verticalLayout_3.addWidget(self.classItem)
        self.scrollableClassesDisplay.setWidget(self.scrollClass)
        self.verticalLayout_5.addWidget(self.scrollableClassesDisplay)
        self.sortBy_2 = QtWidgets.QGroupBox(self.RightSideSchedule)
        self.sortBy_2.setStyleSheet("")
        self.sortBy_2.setObjectName("sortBy_2")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.sortBy_2)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.sortDue_2 = QtWidgets.QComboBox(self.sortBy_2)
        self.sortDue_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.sortDue_2.setObjectName("sortDue_2")
        self.sortDue_2.addItem("")
        self.sortDue_2.addItem("")
        self.sortDue_2.addItem("")
        self.horizontalLayout_27.addWidget(self.sortDue_2)
        self.sortAcend_2 = QtWidgets.QComboBox(self.sortBy_2)
        self.sortAcend_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.sortAcend_2.setObjectName("sortAcend_2")
        self.sortAcend_2.addItem("")
        self.sortAcend_2.addItem("")
        self.horizontalLayout_27.addWidget(self.sortAcend_2)
        self.verticalLayout_5.addWidget(self.sortBy_2)
        self.horizontalLayout_7.addWidget(self.RightSideSchedule)
        self.switchTab.addTab(self.scheduletab, "")

        self.retranslateUi(Form)
        self.switchTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.newHomeworkGroup.setTitle(_translate("Form", "Homework"))
        self.newHWText.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.newHWText.setPlaceholderText(_translate("Form", "Describe your homework... Does it fly? Is it blue? etc "))
        self.newDueGroup.setTitle(_translate("Form", "Due Date"))
        self.radioButton.setText(_translate("Form", "Assignment Repeats?"))
        self.newDifficultyGroup.setTitle(_translate("Form", "Difficulty"))
        self.newClassGroup.setTitle(_translate("Form", "Class"))
        self.newClassToHW.setItemText(0, _translate("Form", "Comp Sci "))
        self.newAdd.setText(_translate("Form", "Add"))
        self.donenametodo.setText(_translate("Form", "Done?"))
        self.blocknametodo.setText(_translate("Form", "Block"))
        self.classnametodo.setText(_translate("Form", "Class"))
        self.diffratingtodo.setText(_translate("Form", "Difficulty"))
        self.progressbartodo.setText(_translate("Form", "Progress"))
        self.dueinnametodo.setText(_translate("Form", "Due"))
        self.infonametodo.setText(_translate("Form", "Info"))
        self.blockName.setText(_translate("Form", "A"))
        self.classname.setText(_translate("Form", "AP Computer Science"))
        self.diffrating.setText(_translate("Form", "6/10"))
        self.dueinName.setText(_translate("Form", "1d"))
        self.extrabtn.setText(_translate("Form", "..."))
        self.sortBy.setTitle(_translate("Form", "Sort By:"))
        self.sortDue.setItemText(0, _translate("Form", "Due Date"))
        self.sortDue.setItemText(1, _translate("Form", "Class"))
        self.sortDue.setItemText(2, _translate("Form", "Difficulty"))
        self.sortAcend.setItemText(0, _translate("Form", "Ascending (A-Z, 1-10)"))
        self.sortAcend.setItemText(1, _translate("Form", "Decending (Z-A, 10-1)"))
        self.sortShowDone.setText(_translate("Form", "Show done"))
        self.switchTab.setTabText(self.switchTab.indexOf(self.todotab), _translate("Form", "Todo List"))
        self.NewClassGroup.setTitle(_translate("Form", "Description"))
        self.newClassroomNum.setPlaceholderText(_translate("Form", "Classroom number"))
        self.newClassName_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.newClassName_2.setPlaceholderText(_translate("Form", "Class Name"))
        self.newClassDesc.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.newClassDesc.setPlaceholderText(_translate("Form", "Describe your class... Does it eat? Is it pink? etc "))
        self.newBlock.setPlaceholderText(_translate("Form", "Block"))
        self.classstartdonetime.setTitle(_translate("Form", "Time Starts        Time Ends"))
        self.isunusual.setText(_translate("Form", "Custom (swap schedule)"))
        self.newAddS.setText(_translate("Form", "Add"))
        self.classtimenamesched.setText(_translate("Form", "Time"))
        self.classblocknamesched.setText(_translate("Form", "Block"))
        self.classnumnamesched.setText(_translate("Form", "Classroom #"))
        self.classnamesched.setText(_translate("Form", "Class"))
        self.classinfonamesched.setText(_translate("Form", "Info"))
        self.time.setText(_translate("Form", "11:45-12:01"))
        self.classBlockTextSched.setText(_translate("Form", "A"))
        self.classNumberNameSched.setText(_translate("Form", "LC 7"))
        self.classNameSched.setText(_translate("Form", "AP Computer Science"))
        self.showExtra.setText(_translate("Form", "..."))
        self.sortBy_2.setTitle(_translate("Form", "Sort By:"))
        self.sortDue_2.setItemText(0, _translate("Form", "Time"))
        self.sortDue_2.setItemText(1, _translate("Form", "Class"))
        self.sortDue_2.setItemText(2, _translate("Form", "Block"))
        self.sortAcend_2.setItemText(0, _translate("Form", "Ascending (A-Z, 1-10)"))
        self.sortAcend_2.setItemText(1, _translate("Form", "Decending (Z-A, 10-1)"))
        self.switchTab.setTabText(self.switchTab.indexOf(self.scheduletab), _translate("Form", "Schedule"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
