defaultPath: "" #leave it blank to default to downloads folder, else you can sepcify path here, example: /Users/YOUR NAME HERE/(downloads, documents, applications etc)
printsProcess: False #pretty sure you don't want to see EVERY file being moved
isEdible: False #shoo shoo qing qing, go away now!