# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ch3.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 160, 201, 151))
        font = QtGui.QFont()
        font.setPointSize(31)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuILUVNOODL = QtWidgets.QMenu(self.menubar)
        self.menuILUVNOODL.setObjectName("menuILUVNOODL")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setShortcut("")
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionCopatatle = QtWidgets.QAction(MainWindow)
        self.actionCopatatle.setObjectName("actionCopatatle")
        self.actionPastedadle = QtWidgets.QAction(MainWindow)
        self.actionPastedadle.setObjectName("actionPastedadle")
        self.actionSEND_NOODS_PLS = QtWidgets.QAction(MainWindow)
        self.actionSEND_NOODS_PLS.setObjectName("actionSEND_NOODS_PLS")
        self.menuFIle.addAction(self.actionSave)
        self.menuFIle.addAction(self.actionLoad)
        self.menuEdit.addAction(self.actionCopatatle)
        self.menuEdit.addAction(self.actionPastedadle)
        self.menuILUVNOODL.addAction(self.actionSEND_NOODS_PLS)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuILUVNOODL.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.actionNew.triggered.connect(lambda: self.clicked("noo"))
        self.actionNew.triggered.connect(lambda: self.clicked("sav"))
        self.actionNew.triggered.connect(lambda: self.clicked("copie"))
        self.actionNew.triggered.connect(lambda: self.clicked("noo"))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "BUMLED"))
        self.menuFIle.setTitle(_translate("MainWindow", "FIle"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuILUVNOODL.setTitle(_translate("MainWindow", "ILUVNOODL"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setStatusTip(_translate("MainWindow", "KEBOOB ON DA CLIFF DA BEST FOOD"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionLoad.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionCopatatle.setText(_translate("MainWindow", "Copatatle"))
        self.actionCopatatle.setStatusTip(_translate("MainWindow", "coPapale a fildadale"))
        self.actionCopatatle.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPastedadle.setText(_translate("MainWindow", "Pastedadle"))
        self.actionPastedadle.setStatusTip(_translate("MainWindow", "pastdadle"))
        self.actionPastedadle.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionSEND_NOODS_PLS.setText(_translate("MainWindow", "SEND NOODS PLS"))

    def clicked(self, text):
        self.label.setText(text)
        self.label.adjustSize()
        self.label.repaint()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
