# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '0or1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(24)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.combotx = QtWidgets.QComboBox(self.centralwidget)
        self.combotx.setGeometry(QtCore.QRect(240, 170, 104, 26))
        self.combotx.setObjectName("combotx")
        self.combotx.addItem("")
        self.combotx.addItem("")
        self.comboty = QtWidgets.QComboBox(self.centralwidget)
        self.comboty.setGeometry(QtCore.QRect(400, 170, 104, 26))
        self.comboty.setObjectName("comboty")
        self.comboty.addItem("")
        self.comboty.addItem("")
        self.hawtchickfrencheyes = QtWidgets.QPushButton(self.centralwidget)
        self.hawtchickfrencheyes.setGeometry(QtCore.QRect(330, 260, 113, 32))
        self.hawtchickfrencheyes.setObjectName("hawtchickfrencheyes")
        self.constapatedprogressbar = QtWidgets.QProgressBar(self.centralwidget)
        self.constapatedprogressbar.setGeometry(QtCore.QRect(40, 100, 721, 23))
        self.constapatedprogressbar.setProperty("value", 1)
        self.constapatedprogressbar.setObjectName("constapatedprogressbar")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 130, 771, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 220, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 60, 411, 16))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.combotx.addItem("pushorcacalé")
        index = self.combotx.findText("pushorcacalé", QtCore.Qt.MatchFixedString)
        self.combotx.setCurrentIndex(index)

        self.hawtchickfrencheyes.clicked.connect(self.pressed)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.combotx.setItemText(0, _translate("MainWindow", "0"))
        self.combotx.setItemText(1, _translate("MainWindow", "1"))
        self.comboty.setItemText(0, _translate("MainWindow", "1"))
        self.comboty.setItemText(1, _translate("MainWindow", "0"))
        self.hawtchickfrencheyes.setText(_translate("MainWindow", "Pushorcabtn"))
        self.label.setText(_translate("MainWindow", "0 or 1?"))
        self.label_2.setText(_translate("MainWindow", "constipated progress bar"))

    def pressed(self):
        x = int(self.combotx.currentText())
        y = int(self.comboty.currentText())
        xor = (x and not y) or (not x and y)

        print(bool(xor)) #dont click pushorca lol program gets mad if u do


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
